import type { Metadata } from "next"
import Link from "next/link"
import { Clock3, MapPin, MessageCircle, Music2 } from "lucide-react"
import { getAreaLandingData, getAreaLinkHref, getAreaWhatsAppUrl, toAreaDisplayPlan } from "@/lib/country-content"
import { getPublishedClassroomVideos } from "@/lib/classroom-videos"
import { countryPages } from "@/components/layout/country-pages-section"
import { austriaLandingConfig, getAustriaWhatsAppUrl } from "@/lib/austria-landing-config"
import { AustriaVideoWindow } from "./austria-video-window"
import { AustriaToneScale } from "./austria-tone-scale"

const canonical = austriaLandingConfig.seo.canonical

export const metadata: Metadata = {
  title: austriaLandingConfig.seo.title,
  description: austriaLandingConfig.seo.description,
  keywords: ["تحفيظ القرآن أونلاين في النمسا", "تحفيظ القرآن في فيينا", "تحفيظ القرآن في غراتس", "تعليم العربية أونلاين في النمسا", "دروس قرآن في لينتس", "تعلم العربية في سالزبورغ", "باقات تحفيظ القرآن باليورو في النمسا"],
  alternates: { canonical, languages: { ar: canonical, "x-default": canonical } },
  openGraph: { title: austriaLandingConfig.seo.title, description: austriaLandingConfig.seo.description, url: canonical, locale: "ar_AT", type: "website", images: [{ url: "https://quran-elhafez.com/images/og-default.webp", width: 1200, height: 630, alt: "أكاديمية الحافظ المتميز في النمسا" }] },
  twitter: { card: "summary_large_image", title: austriaLandingConfig.seo.title, description: austriaLandingConfig.seo.description, images: ["https://quran-elhafez.com/images/og-default.webp"] },
}

export default async function AustriaPage() {
  const [areaData, videos] = await Promise.all([getAreaLandingData("austria"), getPublishedClassroomVideos()])
  const quranPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "quran")
  const arabicPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "arabic")
  const quranPrices = quranPlans.length >= 4 ? quranPlans.slice(0, 4).map((plan) => plan.price) : austriaLandingConfig.quranPrices
  const arabicPrices = arabicPlans.length >= 4 ? arabicPlans.slice(0, 4).map((plan) => plan.price) : austriaLandingConfig.arabicPrices
  const cities = areaData.cities.length ? areaData.cities.map((city) => city.name_ar) : austriaLandingConfig.cities
  const faq = areaData.faq.length ? areaData.faq.map((item) => [item.question_ar, item.answer_ar] as const) : austriaLandingConfig.faq
  const baseContact = getAreaLinkHref(areaData.links, "whatsapp", getAustriaWhatsAppUrl())
  const trialUrl = getAreaWhatsAppUrl(areaData.links, "حصة تجريبية مجانية في النمسا", baseContact)
  const packageUrl = getAreaWhatsAppUrl(areaData.links, "باقات القرآن أو العربية في النمسا", baseContact)
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "WebPage", "@id": `${canonical}#webpage`, url: canonical, name: austriaLandingConfig.seo.title, description: austriaLandingConfig.seo.description, inLanguage: "ar" },
    { "@type": "EducationalOrganization", "@id": `${canonical}#organization`, name: "أكاديمية الحافظ المتميز", url: "https://quran-elhafez.com/", areaServed: { "@type": "Country", name: "Austria" } },
    { "@type": "Course", name: "تحفيظ القرآن أونلاين في النمسا", description: "حصص فردية للحفظ والمراجعة والقراءة عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: quranPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "EUR", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "Course", name: "تأسيس العربية أونلاين في النمسا", description: "حصص فردية لبناء أساس القراءة والفهم بالعربية عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: arabicPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "EUR", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  ] }

  return <main dir="rtl" className="min-h-screen overflow-hidden bg-[#FFF9F2] text-[#2C2438]
    "><header className="border-b border-[#F4DDE5] bg-[#FFF9F2] px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><span className="font-black tracking-wide">النمسا · القرآن والعربية</span><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full bg-[#4B3B67] px-4 py-2 text-sm font-black text-white">احجز الحصة التجريبية</a></div></header>
    <section className="relative overflow-hidden bg-[#4B3B67] px-5 pb-20 pt-16 text-[#FFF9F2] sm:px-8 lg:pb-28"><div className="pointer-events-none absolute inset-0 opacity-20" aria-hidden="true"><div className="absolute -right-10 top-12 h-px w-[120%] rotate-[-9deg] bg-[#C49A45] shadow-[0_34px_0_#C49A45,0_68px_0_#C49A45,0_102px_0_#C49A45]" /><div className="absolute -left-10 bottom-20 h-px w-[120%] rotate-[8deg] bg-[#F4DDE5] shadow-[0_30px_0_#F4DDE5,0_60px_0_#F4DDE5]" /></div><div className="relative mx-auto grid max-w-6xl gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="flex items-center gap-2 text-sm font-black uppercase tracking-[0.25em] text-[#F4DDE5]"><Music2 size={16} /> نوتة البداية · النمسا</p><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[1.08] sm:text-7xl">ابدأ بنغمة واضحة للقرآن والعربية</h1><p className="mt-7 max-w-2xl text-lg leading-9 text-[#FFF9F2]/85">من فيينا وغراتس إلى لينتس وسالزبورغ، حدد هدفك ووقتك ثم تعرف إلى المسار والباقات الشهرية. التواصل مع الأكاديمية باللغة العربية.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#austria-plans" className="rounded-full bg-[#C49A45] px-6 py-3 font-black text-[#2C2438]">اعرض السلم الشهري</a><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full border border-[#FFF9F2] px-6 py-3 font-black">احجز الحصة التجريبية</a></div></div><div className="rounded-[2.5rem] border border-[#F4DDE5]/45 bg-[#2C2438]/20 p-7"><span className="text-7xl">{austriaLandingConfig.flag}</span><p className="mt-6 text-sm font-black text-[#F4DDE5]">تعلم فردي أونلاين</p><p className="mt-2 text-2xl font-black">إيقاع يتسع له يومك.</p><div className="mt-6 grid grid-cols-2 gap-2 text-sm font-bold">{cities.map((city) => <span key={city} className="border-r-2 border-[#C49A45] pr-3">{city}</span>)}</div></div></div></section>
    <section lang="de" className="bg-[#FFF9F2] px-5 py-12 sm:px-8" aria-labelledby="austria-local-card-title"><div className="mx-auto max-w-5xl border-b-4 border-[#C49A45] bg-[#F4DDE5] p-6 text-left text-[#2C2438] sm:p-9"><p className="text-xs font-black tracking-[0.2em] text-[#4B3B67]">{austriaLandingConfig.localCard.title}</p><h2 id="austria-local-card-title" className="mt-3 text-2xl font-black sm:text-3xl">{austriaLandingConfig.localCard.heading}</h2><p className="mt-4 max-w-4xl text-lg leading-8">{austriaLandingConfig.localCard.body}</p></div></section>
    <section className="bg-[#FFF9F2] px-5 py-14 sm:px-8"><div className="mx-auto max-w-6xl"><div className="grid gap-5 md:grid-cols-2"><article className="rounded-[2rem] border-2 border-[#4B3B67]/20 bg-[#F4DDE5] p-7"><span className="text-4xl text-[#C49A45]">♪</span><p className="mt-4 font-black text-[#4B3B67]">تحفيظ القرآن الكريم</p><h2 className="mt-3 text-3xl font-black">إيقاع ثابت للحفظ والمراجعة</h2><p className="mt-4 leading-8 text-[#2C2438]/70">حصص فردية لتنظيم الحفظ والتسميع والمراجعة والقراءة وفق هدف الطالب، مع باقات شهرية واضحة باليورو.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-[#4B3B67] px-5 py-3 font-black text-white">اسأل عن برنامج القرآن</a></article><article className="rounded-[2rem] border-2 border-[#C49A45]/40 bg-[#4B3B67] p-7 text-white"><span className="text-4xl text-[#C49A45]">♫</span><p className="mt-4 font-black text-[#F4DDE5]">تأسيس اللغة العربية</p><h2 className="mt-3 text-3xl font-black">سلم تدريجي للقراءة والفهم</h2><p className="mt-4 leading-8 text-white/80">مسار فردي لبناء أساس القراءة والفهم بالعربية، يبدأ من مستوى الطالب وهدفه التعليمي.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full border-2 border-[#F4DDE5] px-5 py-3 font-black">اسأل عن برنامج العربية</a></article></div></div></section>
    <AustriaVideoWindow videos={videos} />
    <section className="bg-[#FFF9F2] px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-start gap-4"><MapPin className="mt-1 text-[#C49A45]" /><div><p className="text-sm font-black text-[#4B3B67]">السياق المحلي</p><h2 className="mt-2 text-3xl font-black">التعلم أونلاين من مدن النمسا</h2><p className="mt-4 max-w-3xl leading-8 text-[#2C2438]/70">يمكنك التعلم أونلاين من فيينا أو غراتس أو لينتس أو سالزبورغ. ذكر المدينة يوضح نطاق الصفحة ولا يعني وجود فرع محلي.</p><div className="mt-6 flex flex-wrap gap-2">{cities.map((city) => <span key={city} className="rounded-full border border-[#F4DDE5] bg-white px-4 py-2 text-sm font-bold">{city}</span>)}</div><p className="mt-5 flex items-center gap-2 text-sm font-bold text-[#4B3B67]"><Clock3 size={16} /> {areaData.timezones.find((timezone) => timezone.is_primary)?.label_ar || austriaLandingConfig.timezone}</p></div></div></div></section>
    <AustriaToneScale whatsapp={packageUrl} quranPrices={quranPrices} arabicPrices={arabicPrices} />
    <section className="bg-[#2C2438] px-5 py-16 text-[#FFF9F2] sm:px-8"><div className="mx-auto max-w-5xl"><p className="text-sm font-black text-[#C49A45]">فواصل إيقاعية</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">أسئلة قبل بدء النغمة</h2><div className="mt-8 divide-y divide-white/15">{faq.map(([question, answer], index) => <article key={question} className="grid gap-3 py-6 sm:grid-cols-[4rem_1fr]"><span className="font-serif text-3xl text-[#F4DDE5]">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-black text-[#F4DDE5]">{question}</h3><p className="mt-2 leading-7 text-white/75">{answer}</p></div></article>)}</div></div></section>
    <section className="bg-[#C49A45] px-5 py-16 text-center text-[#2C2438] sm:px-8"><div className="mx-auto max-w-3xl"><h2 className="text-4xl font-black">اختر نغمة البداية</h2><p className="mt-4 leading-8">اذكر مدينتك والبرنامج الذي تريده والوقت المناسب لك، وابدأ التواصل باللغة العربية.</p><a href={trialUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#4B3B67] px-6 py-3 font-black text-white"><MessageCircle size={18} /> أريد الحصة التجريبية</a></div></section>
    <footer className="border-t-4 border-[#F4DDE5] bg-[#4B3B67] px-5 py-8 text-[#FFF9F2] sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-black tracking-wide">النمسا · {new Date().getFullYear()}</span><nav aria-label="روابط صفحة النمسا" className="flex flex-wrap gap-x-5 gap-y-2 text-sm font-bold text-[#FFF9F2]/85"><Link href="/">الرئيسية</Link><Link href="/games">الألعاب والمسابقات</Link><Link href="/library">المكتبة</Link><Link href="/contact">التواصل</Link><Link href="/privacy">الخصوصية</Link><Link href="/terms">الشروط</Link></nav></div><details className="mt-6 border-t border-white/15 pt-5"><summary className="cursor-pointer text-sm font-black text-[#F4DDE5]">صفحاتنا حسب الدولة</summary><nav aria-label="كل صفحات الدول" className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{countryPages.map((country) => <Link key={country.href} href={country.href} className="rounded-md border border-white/15 px-3 py-2 text-sm text-[#FFF9F2]/85 transition hover:border-[#C49A45] hover:text-white"><span className="me-2" aria-hidden="true">{country.flag}</span>{country.label}</Link>)}</nav></details></div></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
  </main>
}
