'use client'

import { useState } from "react"
import { ArrowUpLeft, MessageCircle, Sparkles } from "lucide-react"

export function BrazilSlantedPlans({ whatsapp, quranPrices, arabicPrices }: { whatsapp: string; quranPrices: readonly number[]; arabicPrices: readonly number[] }) {
  const [program, setProgram] = useState<"quran" | "arabic">("quran")
  const prices = program === "quran" ? quranPrices : arabicPrices
  const title = program === "quran" ? "تحفيظ القرآن الكريم" : "تأسيس اللغة العربية"
  const sessions = [4, 8, 12, 16]
  return <section id="brazil-plans" className="bg-[#FFF9E8] px-5 py-16 text-[#14251F] sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-sm font-black tracking-[0.2em] text-[#087F5B]"><Sparkles size={16} /> خطتك · على طريقتك</p><h2 className="mt-3 text-4xl font-black sm:text-6xl">اختر المسار ثم حرّك الباقة</h2></div><div className="flex rounded-full border-2 border-[#1756A1] bg-white p-1" role="tablist" aria-label="برامج البرازيل"><button type="button" role="tab" aria-selected={program === "quran"} onClick={() => setProgram("quran")} className={`rounded-full px-4 py-2 text-sm font-black ${program === "quran" ? "bg-[#1756A1] text-white" : "text-[#1756A1]"}`}>القرآن</button><button type="button" role="tab" aria-selected={program === "arabic"} onClick={() => setProgram("arabic")} className={`rounded-full px-4 py-2 text-sm font-black ${program === "arabic" ? "bg-[#087F5B] text-white" : "text-[#087F5B]"}`}>العربية</button></div></div><p className="mt-4 max-w-2xl leading-8 text-[#14251F]/70">{title} بحصة أساسية مدتها 30 دقيقة، وباقات شهرية واضحة بالريال البرازيلي.</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{sessions.map((count, index) => <article key={count} className={`relative min-h-64 overflow-hidden rounded-[2rem] border-4 border-[#14251F] bg-white p-6 shadow-[8px_8px_0_#F6C945] ${index % 2 ? "rotate-2" : "-rotate-2"}`}><span className="absolute -left-4 -top-5 text-7xl font-black text-[#087F5B]/10">{count}</span><div className="relative"><p className="text-sm font-black text-[#1756A1]">{count} حصص شهريًا</p><h3 className="mt-4 text-2xl font-black">{index === 0 ? "بداية مرنة" : index === 1 ? "روتين ثابت" : index === 2 ? "تقدم متوازن" : "خطة مكثفة"}</h3><p className="mt-3 text-sm font-bold text-[#14251F]/65">{["مرة أسبوعيًا", "مرتان أسبوعيًا", "ثلاث مرات أسبوعيًا", "أربع مرات أسبوعيًا"][index]}</p><strong className="mt-6 block text-4xl font-black text-[#087F5B]">R${prices[index]}</strong><a href={whatsapp} target="_blank" rel="noreferrer" aria-label={`اسأل عن باقة ${count} حصص`} className="absolute bottom-0 left-0 inline-flex items-center gap-1 rounded-full bg-[#14251F] px-3 py-2 text-xs font-black text-white"><MessageCircle size={14} /> اسأل</a></div></article>)}</div><div className="mt-10 flex flex-wrap gap-3"><p className="rounded-xl bg-[#F6C945] px-5 py-3 font-black">يوجد باقات مخصصة.</p><p className="rounded-xl border-2 border-[#1756A1] px-5 py-3 font-black">خصم 10٪ للأخوات والإحالة</p></div></div></section>
}
