import type { Metadata } from "next"
import Link from "next/link"
import { Clock3, MapPin, MessageCircle, Sparkles } from "lucide-react"
import { getAreaLandingData, getAreaLinkHref, getAreaWhatsAppUrl, toAreaDisplayPlan } from "@/lib/country-content"
import { getPublishedClassroomVideos } from "@/lib/classroom-videos"
import { countryPages } from "@/components/layout/country-pages-section"
import { brazilLandingConfig, getBrazilWhatsAppUrl } from "@/lib/brazil-landing-config"
import { BrazilSlantedPlans } from "./brazil-slanted-plans"
import { BrazilVideoCollage } from "./brazil-video-collage"

const canonical = brazilLandingConfig.seo.canonical
export const metadata: Metadata = {
  title: brazilLandingConfig.seo.title, description: brazilLandingConfig.seo.description,
  keywords: ["تحفيظ القرآن أونلاين في البرازيل", "تحفيظ القرآن في ساو باولو", "تحفيظ القرآن في ريو دي جانيرو", "تعليم العربية أونلاين في البرازيل", "دروس قرآن في برازيليا", "باقات تحفيظ القرآن بالريال البرازيلي"],
  alternates: { canonical, languages: { ar: canonical, "x-default": canonical } },
  openGraph: { title: brazilLandingConfig.seo.title, description: brazilLandingConfig.seo.description, url: canonical, locale: "ar_BR", type: "website", images: [{ url: "https://quran-elhafez.com/images/og-default.webp", width: 1200, height: 630, alt: "أكاديمية الحافظ المتميز في البرازيل" }] },
  twitter: { card: "summary_large_image", title: brazilLandingConfig.seo.title, description: brazilLandingConfig.seo.description, images: ["https://quran-elhafez.com/images/og-default.webp"] },
}

export default async function BrazilPage() {
  const [areaData, videos] = await Promise.all([getAreaLandingData("brazil"), getPublishedClassroomVideos()])
  const quranPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "quran")
  const arabicPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "arabic")
  const quranPrices = quranPlans.length >= 4 ? quranPlans.slice(0, 4).map((plan) => plan.price) : brazilLandingConfig.quranPrices
  const arabicPrices = arabicPlans.length >= 4 ? arabicPlans.slice(0, 4).map((plan) => plan.price) : brazilLandingConfig.arabicPrices
  const cities = areaData.cities.length ? areaData.cities.map((city) => city.name_ar) : brazilLandingConfig.cities
  const faq = areaData.faq.length ? areaData.faq.map((item) => [item.question_ar, item.answer_ar] as const) : brazilLandingConfig.faq
  const baseContact = getAreaLinkHref(areaData.links, "whatsapp", getBrazilWhatsAppUrl())
  const trialUrl = getAreaWhatsAppUrl(areaData.links, "حصة تجريبية مجانية في البرازيل", baseContact)
  const packageUrl = getAreaWhatsAppUrl(areaData.links, "باقات القرآن أو العربية في البرازيل", baseContact)
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "WebPage", "@id": `${canonical}#webpage`, url: canonical, name: brazilLandingConfig.seo.title, description: brazilLandingConfig.seo.description, inLanguage: "ar" },
    { "@type": "EducationalOrganization", "@id": `${canonical}#organization`, name: "أكاديمية الحافظ المتميز", url: "https://quran-elhafez.com/", areaServed: { "@type": "Country", name: "Brazil" } },
    { "@type": "Course", name: "تحفيظ القرآن أونلاين في البرازيل", description: "حصص فردية للحفظ والمراجعة والقراءة عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: quranPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "BRL", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "Course", name: "تأسيس العربية أونلاين في البرازيل", description: "حصص فردية لبناء أساس القراءة والفهم بالعربية عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: arabicPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "BRL", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  ] }
  return <main dir="rtl" className="min-h-screen overflow-hidden bg-[#FFF9E8] text-[#14251F]"><header className="border-b-4 border-[#F6C945] bg-[#087F5B] px-5 py-4 text-white sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><span className="font-black">البرازيل · القرآن والعربية</span><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full bg-[#F6C945] px-4 py-2 text-sm font-black text-[#14251F]">احجز الحصة التجريبية</a></div></header>
  <section className="bg-[#FFF9E8] px-5 py-12 sm:px-8"><div className="mx-auto grid max-w-6xl gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-[3rem] bg-[#087F5B] p-8 text-white shadow-[12px_12px_0_#F6C945] sm:p-14"><p className="flex items-center gap-2 text-sm font-black tracking-[0.2em] text-[#F6C945]"><Sparkles size={16} /> البرازيل · أونلاين</p><h1 className="mt-6 text-5xl font-black leading-[1.05] sm:text-7xl">تعلمك يبدأ من المكان الذي أنت فيه</h1><p className="mt-6 max-w-2xl text-lg leading-9 text-white/85">من ساو باولو وريو دي جانيرو إلى برازيليا وسالڤادور، تعلّم القرآن أو أسّس لغتك العربية بحصص فردية أونلاين. التواصل مع الأكاديمية باللغة العربية.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#brazil-plans" className="rounded-full bg-[#F6C945] px-6 py-3 font-black text-[#14251F]">اكتشف الباقات</a><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full border-2 border-white px-6 py-3 font-black">احجز الحصة التجريبية</a></div></div><div className="grid gap-5"><div className="rotate-2 rounded-[2.5rem] bg-[#F6C945] p-7"><span className="text-5xl font-black text-[#1756A1]">01</span><h2 className="mt-3 text-2xl font-black">هدف واضح</h2><p className="mt-3 leading-8">حدد البرنامج الذي تريد البدء به، ثم ابدأ من مستواك الحالي.</p></div><div className="-rotate-2 rounded-[2.5rem] bg-[#1756A1] p-7 text-white"><span className="text-5xl font-black text-[#F6C945]">02</span><h2 className="mt-3 text-2xl font-black">حصة فردية</h2><p className="mt-3 leading-8 text-white/85">تعلم أونلاين بخطة تناسب وقتك، مع تواصل عربي واضح.</p></div></div></div></section>
  <section lang="pt-BR" className="bg-[#FFF9E8] px-5 py-10 sm:px-8" aria-labelledby="brazil-local-card-title"><div className="mx-auto max-w-6xl rounded-[2.5rem] border-4 border-[#1756A1] bg-white p-7 text-left shadow-[9px_9px_0_#F6C945] sm:p-10"><p className="text-xs font-black tracking-[0.2em] text-[#087F5B]">{brazilLandingConfig.localCard.title}</p><h2 id="brazil-local-card-title" className="mt-3 text-2xl font-black sm:text-3xl">{brazilLandingConfig.localCard.heading}</h2><p className="mt-4 max-w-5xl text-lg leading-8">{brazilLandingConfig.localCard.body}</p></div></section>
  <section className="bg-[#FFF9E8] px-5 py-14 sm:px-8"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-2"><article className="-rotate-1 rounded-[2.5rem] border-4 border-[#087F5B] bg-[#E2F4EA] p-8"><h2 className="text-3xl font-black text-[#087F5B]">تحفيظ القرآن الكريم</h2><p className="mt-4 leading-8">روتين فردي للحفظ والتسميع والمراجعة والقراءة، مع باقات شهرية بالريال البرازيلي.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-[#087F5B] px-5 py-3 font-black text-white">اسأل عن برنامج القرآن</a></article><article className="rotate-1 rounded-[2.5rem] border-4 border-[#1756A1] bg-[#E8F0FF] p-8"><h2 className="text-3xl font-black text-[#1756A1]">تأسيس اللغة العربية</h2><p className="mt-4 leading-8">مسار تدريجي لبناء أساس القراءة والفهم بالعربية، يبدأ من هدف الطالب ومستواه.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-[#1756A1] px-5 py-3 font-black text-white">اسأل عن برنامج العربية</a></article></div></section>
  <BrazilVideoCollage videos={videos} /><BrazilSlantedPlans whatsapp={packageUrl} quranPrices={quranPrices} arabicPrices={arabicPrices} />
  <section className="bg-[#F6C945] px-5 py-14 sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-start gap-4"><MapPin className="mt-1 text-[#1756A1]" /><div><p className="text-sm font-black text-[#1756A1]">نطاق الصفحة</p><h2 className="mt-2 text-3xl font-black">تعلم أونلاين من مدن البرازيل</h2><p className="mt-4 max-w-3xl leading-8">يمكنك التعلم أونلاين من ساو باولو أو ريو دي جانيرو أو برازيليا أو سالڤادور. المدن سياق جغرافي للصفحة فقط، ولا توجد بها مقرات أو فروع أو أماكن تدريس تابعة للأكاديمية.</p><div className="mt-6 flex flex-wrap gap-2">{cities.map((city) => <span key={city} className="rounded-full bg-white px-4 py-2 text-sm font-bold">{city}</span>)}</div><p className="mt-5 flex items-center gap-2 text-sm font-bold text-[#1756A1]"><Clock3 size={16} /> {areaData.timezones.find((timezone) => timezone.is_primary)?.label_ar || brazilLandingConfig.timezone}</p></div></div></div></section>
  <section className="bg-[#FFF9E8] px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-black text-[#087F5B]">أسئلة على هيئة ملصقات</p><h2 className="mt-3 text-4xl font-black">اختر الملصق الذي يهمك</h2><div className="mt-8 flex flex-wrap gap-4">{faq.map(([question, answer], index) => <details key={question} className={`max-w-md rounded-3xl border-4 border-[#14251F] p-5 shadow-[6px_6px_0_${index % 2 ? "#1756A1" : "#F6C945"}] ${index % 2 ? "rotate-1 bg-[#E8F0FF]" : "-rotate-1 bg-white"}`}><summary className="cursor-pointer font-black"><span className="me-3 text-[#087F5B]">0{index + 1}</span>{question}</summary><p className="mt-4 leading-7">{answer}</p></details>)}</div></div></section>
  <section className="bg-[#087F5B] px-5 py-16 text-center text-white sm:px-8"><div className="mx-auto max-w-3xl"><h2 className="text-4xl font-black">ابدأ من سؤالك</h2><p className="mt-4 leading-8">اذكر مدينتك والبرنامج الذي تريده والوقت المناسب لك، وابدأ التواصل باللغة العربية.</p><a href={trialUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#F6C945] px-6 py-3 font-black text-[#14251F]"><MessageCircle size={18} /> أريد الحصة التجريبية</a></div></section>
  <footer className="border-t-8 border-[#F6C945] bg-[#14251F] px-5 py-8 text-white sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-black">البرازيل · {new Date().getFullYear()}</span><nav aria-label="روابط صفحة البرازيل" className="flex flex-wrap gap-x-5 gap-y-2 text-sm font-bold text-white/85"><Link href="/">الرئيسية</Link><Link href="/games">الألعاب والمسابقات</Link><Link href="/library">المكتبة</Link><Link href="/contact">التواصل</Link><Link href="/privacy">الخصوصية</Link><Link href="/terms">الشروط</Link></nav></div><details className="mt-6 border-t border-white/15 pt-5"><summary className="cursor-pointer text-sm font-black text-[#F6C945]">صفحاتنا حسب الدولة</summary><nav aria-label="كل صفحات الدول" className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{countryPages.map((country) => <Link key={country.href} href={country.href} className="rounded-md border border-white/15 px-3 py-2 text-sm text-white/85 transition hover:border-[#F6C945] hover:text-white"><span className="me-2" aria-hidden="true">{country.flag}</span>{country.label}</Link>)}</nav></details></div></footer><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></main>
}
