import type { Metadata } from "next"
import Link from "next/link"
import Image from "next/image"
import { Check, MessageCircle } from "lucide-react"
import { getSeoAlternates } from "@/lib/seo-metadata"
import { CountryPagesSection } from "@/components/layout/country-pages-section"
import KuwaitProgramSelector from "./kuwait-program-selector"
import { getKuwaitWhatsAppUrl, kuwaitFaqs, kuwaitLandingConfig } from "@/lib/kuwait-landing-config"

export const metadata: Metadata = {
  title: kuwaitLandingConfig.seo.title,
  description: kuwaitLandingConfig.seo.description,
  keywords: ["تحفيظ القرآن أونلاين الكويت", "تحفيظ القرآن في الكويت", "دروس قرآن أونلاين الكويت", "تأسيس اللغة العربية أونلاين الكويت"],
  alternates: getSeoAlternates(kuwaitLandingConfig.seo.canonical),
  openGraph: { title: kuwaitLandingConfig.seo.socialTitle, description: kuwaitLandingConfig.seo.socialDescription, url: kuwaitLandingConfig.seo.canonical, locale: "ar_KW", type: "website", images: [{ url: "https://quran-elhafez.com/images/og-default.webp", width: 1200, height: 630, alt: "أكاديمية الحافظ المتميز لتحفيظ القرآن وتأسيس اللغة العربية أونلاين في الكويت" }] },
  twitter: { card: "summary_large_image", title: kuwaitLandingConfig.seo.socialTitle, description: kuwaitLandingConfig.seo.socialDescription, images: ["https://quran-elhafez.com/images/og-default.webp"] },
}

const whatsappUrl = getKuwaitWhatsAppUrl("طلب الحصة التجريبية المجانية")

export default function KuwaitPage() {
  return <main dir="rtl" className="min-h-screen overflow-hidden bg-kw-bg text-kw-ink">
    <header className="border-b border-kw-line bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 py-3 sm:px-8"><Link href="/" className="flex items-center gap-3"><Image src="/logo.png" alt="شعار أكاديمية الحافظ المتميز" width={44} height={44} className="size-11 rounded-lg bg-kw-gold object-contain" /><span className="font-bold text-kw-green">أكاديمية الحافظ المتميز</span></Link><span className="text-2xl" role="img" aria-label="الكويت">🇰🇼</span></div></header>
    <section className="relative border-b border-kw-line bg-kw-bg px-5 py-16 sm:px-8 lg:py-24"><div className="mx-auto max-w-4xl text-center"><p className="font-semibold tracking-wide text-kw-gold">كن حافظًا، كن متميزًا</p><h1 className="mt-5 text-balance text-4xl font-bold leading-tight text-kw-green sm:text-6xl">اختر برنامجك، وابدأ طريقك مع القرآن والعربية في الكويت</h1><p className="mx-auto mt-6 max-w-2xl text-pretty text-lg leading-8 text-kw-muted">حصص فردية أونلاين للناطقين بالعربية، صممت لتساعد الطالب على التعلم بخطة واضحة ووقت يناسب الأسرة.</p><p className="mt-4 leading-8 text-kw-muted">تحفيظ القرآن أو تأسيس اللغة العربية — اختر المسار الذي يناسبك.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href={whatsappUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-kw-green px-5 py-3 font-bold text-white transition hover:bg-kw-green-dark focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-kw-gold focus-visible:ring-offset-2"><MessageCircle className="size-4" />احجز الحصة التجريبية المجانية</a><a href="#programs" className="inline-flex min-h-11 items-center rounded-xl border border-kw-green px-5 py-3 font-bold text-kw-green transition hover:bg-kw-green hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-kw-gold focus-visible:ring-offset-2">اختر برنامجك</a></div></div></section>
    <KuwaitProgramSelector />
    <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><div className="text-center"><h2 className="text-3xl font-bold text-kw-green">ماذا يتضمن البرنامج؟</h2></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{["حصة فردية تناسب مستوى الطالب.", "أهداف واضحة لكل مرحلة من التعلم.", "تواصل مباشر عبر الإنترنت.", "اختيار البرنامج قبل عرض الباقات.", "مواعيد تُنسق حسب البرنامج والتوفر."].map((item) => <div key={item} className="rounded-2xl border border-kw-line bg-white p-5 text-center"><Check className="mx-auto size-5 text-kw-gold" /><p className="mt-3 text-sm font-semibold leading-7">{item}</p></div>)}</div></section>
    <section className="border-y border-kw-line bg-white px-5 py-10 text-center"><p className="text-lg font-bold text-kw-green">خصم 10٪ للأخوات والإحالة</p><p className="mt-3 font-semibold text-kw-gold">يوجد باقات مخصصة</p></section>
    <section className="mx-auto max-w-4xl px-5 py-16 text-center sm:px-8"><h2 className="text-3xl font-bold text-kw-green">ابدأ بالخطوة الأولى</h2><p className="mt-4 leading-8 text-kw-muted">اختر البرنامج المناسب ثم تواصل معنا لحجز الحصة التجريبية المجانية.</p><a href={whatsappUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex min-h-11 items-center gap-2 rounded-xl bg-kw-green px-6 py-3 font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-kw-gold focus-visible:ring-offset-2"><MessageCircle className="size-4" />احجز الحصة التجريبية المجانية</a></section>
    <section className="bg-kw-surface px-5 py-16 sm:px-8"><div className="mx-auto max-w-4xl"><h2 className="text-center text-3xl font-bold text-kw-green">الأسئلة الشائعة</h2><div className="mt-8 grid gap-3">{kuwaitFaqs.map(([question, answer]) => <details key={question} className="rounded-xl border border-kw-line bg-white p-5"><summary className="cursor-pointer font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-kw-gold">{question}</summary><p className="mt-3 leading-8 text-kw-muted">{answer}</p></details>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-5 py-16 text-center sm:px-8"><h2 className="text-3xl font-bold text-kw-green">حصص أونلاين للعائلات في مختلف مناطق الكويت</h2><p className="mt-5 leading-8 text-kw-muted">نوفر تجربة تعلم أونلاين للطلاب والعائلات في مدينة الكويت وحولي والفروانية والأحمدي ومبارك الكبير وغيرها من المناطق، مع تنسيق المواعيد حسب البرنامج والتوفر.</p></section>
    <footer className="bg-kw-green px-5 py-10 text-white sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-5"><div className="flex items-center gap-3"><Image src="/logo.png" alt="شعار أكاديمية الحافظ المتميز" width={44} height={44} className="size-11 rounded-lg bg-kw-gold object-contain" /><div><p className="font-bold">أكاديمية الحافظ المتميز</p><p className="mt-1 text-sm text-white/75">برامج القرآن والعربية أونلاين في الكويت</p></div></div><nav aria-label="روابط صفحة الكويت" className="flex flex-wrap gap-x-5 gap-y-3 text-sm text-white/85"><Link href="/quran">/quran</Link><Link href="/arabic">/arabic</Link><Link href="/pricing">/pricing</Link><Link href="/teachers">/teachers</Link><Link href="/library">/library</Link><Link href="/blog">/blog</Link><Link href="/privacy">/privacy</Link><Link href="/terms">/terms</Link><Link href="/refund-policy">/refund-policy</Link></nav></div><CountryPagesSection /></div></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: kuwaitFaqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }) }} />
  </main>
}
