import type { Metadata } from "next"
import Link from "next/link"
import { Clock3, MapPin, MessageCircle } from "lucide-react"
import { getAreaLandingData, getAreaLinkHref, getAreaWhatsAppUrl, toAreaDisplayPlan } from "@/lib/country-content"
import { getPublishedClassroomVideos } from "@/lib/classroom-videos"
import { countryPages } from "@/components/layout/country-pages-section"
import { norwayLandingConfig, getNorwayWhatsAppUrl } from "@/lib/norway-landing-config"
import { NorwayVideoPanel } from "./norway-video-panel"
import { NorwaySubscriptionScale } from "./norway-subscription-scale"

const canonical = norwayLandingConfig.seo.canonical

export const metadata: Metadata = {
  title: norwayLandingConfig.seo.title,
  description: norwayLandingConfig.seo.description,
  keywords: ["تحفيظ القرآن أونلاين في النرويج", "تحفيظ القرآن في أوسلو", "تحفيظ القرآن في بيرغن", "تعليم العربية أونلاين في النرويج", "دروس قرآن في تروندهايم", "تعلم العربية في ستافنجر", "باقات تحفيظ القرآن بالكرونة النرويجية"],
  alternates: { canonical, languages: { ar: canonical, "x-default": canonical } },
  openGraph: { title: norwayLandingConfig.seo.title, description: norwayLandingConfig.seo.description, url: canonical, locale: "ar_NO", type: "website", images: [{ url: "https://quran-elhafez.com/images/og-default.webp", width: 1200, height: 630, alt: "أكاديمية الحافظ المتميز في النرويج" }] },
  twitter: { card: "summary_large_image", title: norwayLandingConfig.seo.title, description: norwayLandingConfig.seo.description, images: ["https://quran-elhafez.com/images/og-default.webp"] },
}

export default async function NorwayPage() {
  const [areaData, videos] = await Promise.all([getAreaLandingData("norway"), getPublishedClassroomVideos()])
  const quranPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "quran")
  const arabicPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "arabic")
  const quranPrices = quranPlans.length >= 4 ? quranPlans.slice(0, 4).map((plan) => plan.price) : norwayLandingConfig.quranPrices
  const arabicPrices = arabicPlans.length >= 4 ? arabicPlans.slice(0, 4).map((plan) => plan.price) : norwayLandingConfig.arabicPrices
  const cities = areaData.cities.length ? areaData.cities.map((city) => city.name_ar) : norwayLandingConfig.cities
  const faq = areaData.faq.length ? areaData.faq.map((item) => [item.question_ar, item.answer_ar] as const) : norwayLandingConfig.faq
  const baseContact = getAreaLinkHref(areaData.links, "whatsapp", getNorwayWhatsAppUrl())
  const trialUrl = getAreaWhatsAppUrl(areaData.links, "حصة تجريبية مجانية في النرويج", baseContact)
  const packageUrl = getAreaWhatsAppUrl(areaData.links, "باقات القرآن أو العربية في النرويج", baseContact)
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "WebPage", "@id": `${canonical}#webpage`, url: canonical, name: norwayLandingConfig.seo.title, description: norwayLandingConfig.seo.description, inLanguage: "ar" },
    { "@type": "EducationalOrganization", "@id": `${canonical}#organization`, name: "أكاديمية الحافظ المتميز", url: "https://quran-elhafez.com/", areaServed: { "@type": "Country", name: "Norway" } },
    { "@type": "Course", name: "تحفيظ القرآن أونلاين في النرويج", description: "حصص فردية للحفظ والمراجعة والقراءة عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: quranPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "NOK", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "Course", name: "تأسيس العربية أونلاين في النرويج", description: "حصص فردية لبناء أساس القراءة والفهم بالعربية عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: arabicPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "NOK", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  ] }

  return <main dir="rtl" className="min-h-screen overflow-hidden bg-[#F4F8F7] text-[#234B5A]">
    <header className="border-b border-[#C7D5D8] bg-[#F4F8F7] px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><span className="font-black tracking-wide">النرويج · القرآن والعربية</span><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full bg-[#234B5A] px-4 py-2 text-sm font-black text-white">احجز الحصة التجريبية</a></div></header>
    <section className="relative overflow-hidden bg-[#F4F8F7] px-5 pb-20 pt-16 sm:px-8 lg:pb-28"><div className="pointer-events-none absolute inset-x-0 top-0 h-72 bg-[radial-gradient(ellipse_at_top,#C7D5D8_0%,#F4F8F7_68%)] opacity-80" aria-hidden="true" /><div className="relative mx-auto max-w-6xl"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.26em] text-[#58756B]">دفتر يوميات هادئ · النرويج</p><h1 className="mt-6 text-5xl font-black leading-[1.08] sm:text-7xl">خطوة هادئة تبني عادة للقرآن والعربية</h1><p className="mt-7 max-w-2xl text-lg leading-9 text-[#234B5A]/75">من أوسلو وبيرغن إلى تروندهايم وستافنجر، ابدأ بتحديد هدفك ووقتك. تعرّف إلى المسار المناسب ثم تواصل معنا للحصة التجريبية باللغة العربية.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#norway-plans" className="rounded-full bg-[#58756B] px-6 py-3 font-black text-white">تصفح مقياس الشهر</a><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full border-2 border-[#234B5A] px-6 py-3 font-black">ابدأ بالحصة التجريبية</a></div></div><div className="mt-14 grid max-w-4xl gap-4 border-y border-[#C7D5D8] py-6 sm:grid-cols-3"><div><span className="text-xs font-black text-[#58756B]">01 · الهدف</span><p className="mt-2 font-bold">حدد ما تريد أن تتعلمه</p></div><div><span className="text-xs font-black text-[#58756B]">02 · الوقت</span><p className="mt-2 font-bold">اختر وقتًا يناسب يومك</p></div><div><span className="text-xs font-black text-[#58756B]">03 · البداية</span><p className="mt-2 font-bold">تواصل معنا بالعربية</p></div></div></div></section>
    <section lang="no" className="border-y border-[#C7D5D8] bg-white px-5 py-12 sm:px-8" aria-labelledby="norway-local-card-title"><div className="mx-auto max-w-5xl border-r-4 border-[#58756B] bg-[#F4F8F7] p-6 sm:p-9"><p className="text-xs font-black tracking-[0.2em] text-[#58756B]">{norwayLandingConfig.localCard.title}</p><h2 id="norway-local-card-title" className="mt-3 text-2xl font-black sm:text-3xl">{norwayLandingConfig.localCard.heading}</h2><p className="mt-4 max-w-4xl text-lg leading-8">{norwayLandingConfig.localCard.body}</p></div></section>
    <section className="bg-[#234B5A] px-5 py-14 text-[#F4F8F7] sm:px-8"><div className="mx-auto grid max-w-6xl gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-black text-[#C5965A]">المرونة اليومية</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">وقت التعلم يأخذ مكانه داخل يومك</h2><p className="mt-4 max-w-2xl leading-8 text-[#F4F8F7]/75">تبدأ الحصة من هدف الطالب ووقته المتاح. اذكر مدينتك والتوقيت المناسب، وسيتم التواصل معك باللغة العربية لتنسيق الخطوة التالية.</p></div><div className="rounded-2xl border border-[#C7D5D8]/30 p-6 text-center"><Clock3 className="mx-auto text-[#C5965A]" /><p className="mt-3 font-black">Europe/Oslo</p><p className="mt-1 text-sm text-[#F4F8F7]/65">توقيت أوسلو</p></div></div></section>
    <NorwayVideoPanel videos={videos} />
    <section className="bg-white px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-black text-[#58756B]">مادتان واضحتان</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">تعلم فردي أونلاين</h2><div className="mt-9 grid gap-6 md:grid-cols-2"><article className="border-t-4 border-[#C5965A] bg-[#F4F8F7] p-7"><p className="font-black text-[#58756B]">تحفيظ القرآن الكريم</p><h3 className="mt-3 text-3xl font-black">حفظ ومراجعة ضمن عادة ثابتة</h3><p className="mt-4 leading-8 text-[#234B5A]/70">برنامج فردي للحفظ والتسميع والمراجعة والقراءة، مع إيقاع شهري واضح وباقات بالكرونة النرويجية.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-[#234B5A] px-5 py-3 font-black text-white">اسأل عن برنامج القرآن</a></article><article className="border-t-4 border-[#58756B] bg-[#C7D5D8]/40 p-7"><p className="font-black text-[#C5965A]">تأسيس اللغة العربية</p><h3 className="mt-3 text-3xl font-black">قراءة وفهم من أساس واضح</h3><p className="mt-4 leading-8 text-[#234B5A]/70">مسار فردي تدريجي للطالب الذي يريد بناء أساس القراءة والفهم بالعربية، بدءًا من هدفه الحقيقي.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full border-2 border-[#234B5A] px-5 py-3 font-black">اسأل عن برنامج العربية</a></article></div></div></section>
    <section className="bg-[#F4F8F7] px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-start gap-4"><MapPin className="mt-1 text-[#C5965A]" /><div><p className="text-sm font-black text-[#58756B]">مدن في سياق الصفحة</p><h2 className="mt-2 text-3xl font-black">الدراسة أونلاين من النرويج</h2><p className="mt-4 max-w-3xl leading-8 text-[#234B5A]/70">يمكنك التعلم أونلاين من أوسلو أو بيرغن أو تروندهايم أو ستافنجر. ذكر المدن يوضح نطاق الاستهداف ولا يعني وجود فرع محلي.</p><div className="mt-6 flex flex-wrap gap-2">{cities.map((city) => <span key={city} className="rounded-full border border-[#C7D5D8] bg-white px-4 py-2 text-sm font-bold">{city}</span>)}</div></div></div></div></section>
    <NorwaySubscriptionScale whatsapp={packageUrl} quranPrices={quranPrices} arabicPrices={arabicPrices} />
    <section className="bg-white px-5 py-16 sm:px-8"><div className="mx-auto max-w-4xl"><p className="text-sm font-black text-[#58756B]">إجابات قصيرة</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">قبل أن تبدأ</h2><div className="mt-8 divide-y divide-[#C7D5D8]">{faq.map(([question, answer]) => <article key={question} className="grid gap-2 py-6 sm:grid-cols-[.75fr_1.25fr]"><h3 className="font-black">{question}</h3><p className="leading-8 text-[#234B5A]/70">{answer}</p></article>)}</div></div></section>
    <section className="bg-[#58756B] px-5 py-16 text-center text-white sm:px-8"><div className="mx-auto max-w-3xl"><h2 className="text-4xl font-black">اكتب هدفك ووقتك</h2><p className="mt-4 leading-8">اذكر مدينتك والبرنامج الذي تريده والوقت المناسب لك، وابدأ التواصل باللغة العربية.</p><a href={trialUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#234B5A] px-6 py-3 font-black"><MessageCircle size={18} /> أريد الحصة التجريبية</a></div></section>
    <footer className="bg-[#234B5A] px-5 py-8 text-[#F4F8F7] sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-black">النرويج · {new Date().getFullYear()}</span><nav aria-label="روابط صفحة النرويج" className="flex flex-wrap gap-x-5 gap-y-2 text-sm font-bold text-[#F4F8F7]/85"><Link href="/">الرئيسية</Link><Link href="/games">الألعاب والمسابقات</Link><Link href="/library">المكتبة</Link><Link href="/contact">التواصل</Link><Link href="/privacy">الخصوصية</Link><Link href="/terms">الشروط</Link></nav></div><details className="mt-6 border-t border-[#C7D5D8]/20 pt-5"><summary className="cursor-pointer text-sm font-black text-[#C5965A]">صفحاتنا حسب الدولة</summary><nav aria-label="كل صفحات الدول" className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{countryPages.map((country) => <Link key={country.href} href={country.href} className="rounded-md border border-[#C7D5D8]/20 px-3 py-2 text-sm text-[#F4F8F7]/85 transition hover:border-[#C5965A] hover:text-white"><span className="me-2" aria-hidden="true">{country.flag}</span>{country.label}</Link>)}</nav></details></div></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
  </main>
}
