'use client'

import { useState } from "react"
import { MessageCircle } from "lucide-react"

export function FinlandFocusPricing({ quranPrices, arabicPrices, whatsapp }: { quranPrices: readonly number[]; arabicPrices: readonly number[]; whatsapp: string }) {
  const [program, setProgram] = useState<"quran" | "arabic">("quran")
  const prices = program === "quran" ? quranPrices : arabicPrices
  const label = program === "quran" ? "تحفيظ القرآن الكريم" : "تأسيس اللغة العربية"
  return <section className="bg-[#F8FAFC] px-5 py-20 sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-sm font-black tracking-[0.22em] text-[#183B56]">مساحة التركيز · الأسعار</p><h2 className="mt-3 text-4xl font-black text-[#183B56] sm:text-6xl">اختر إيقاع الدراسة بهدوء</h2></div><div className="flex gap-2 rounded-full border border-[#B9D9E8] bg-white p-1"><button type="button" onClick={() => setProgram("quran")} className={`rounded-full px-5 py-2 font-black ${program === "quran" ? "bg-[#183B56] text-white" : "text-[#183B56]"}`}>القرآن</button><button type="button" onClick={() => setProgram("arabic")} className={`rounded-full px-5 py-2 font-black ${program === "arabic" ? "bg-[#183B56] text-white" : "text-[#183B56]"}`}>العربية</button></div></div><p className="mt-8 max-w-2xl text-lg leading-8">{label} · 30 دقيقة للحصة · الأسعار باليورو</p><div className="mt-12 grid gap-0 border-y border-[#183B56]/20 sm:grid-cols-4">{prices.map((price, index) => <div key={price} className="border-b border-[#183B56]/15 px-4 py-8 last:border-b-0 sm:border-b-0 sm:border-l sm:first:border-r sm:last:border-l-0"><span className="text-sm font-bold text-[#183B56]/70">{index + 1} · {(index + 1) * 4} حصص</span><strong className="mt-3 block text-6xl font-black tracking-tight text-[#183B56]">{price}<span className="text-2xl">€</span></strong><span className="mt-2 block text-sm">{index === 0 ? "مرة أسبوعيًا" : index === 1 ? "مرتان أسبوعيًا" : index === 2 ? "ثلاث مرات أسبوعيًا" : "أربع مرات أسبوعيًا"}</span><a href={`${whatsapp}?text=${encodeURIComponent(`أرغب في الاستفسار عن ${label} وباقة ${price} يورو`)}`} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-black text-[#183B56] underline underline-offset-4"><MessageCircle size={15} /> اسأل عن الباقة</a></div>)}</div><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full bg-[#183B56] px-5 py-3 font-black text-white">يوجد باقات مخصصة.</span><span className="rounded-full bg-[#E7D878] px-5 py-3 font-black text-[#183B56]">خصم 10٪ للأخوات والإحالة</span></div></div></section>
}
