export const argentinaLandingConfig = {
  slug: "argentina", name: "الأرجنتين", nameEn: "Argentina", flag: "🇦🇷", currencyCode: "ARS", currencySymbol: "ARS",
  cities: ["بوينس آيرس", "قرطبة", "روساريو", "مندوزا"], timezone: "توقيت الأرجنتين (America/Argentina/Buenos_Aires)",
  quranPrices: [22871, 42693, 64039, 83861], arabicPrices: [30495, 54891, 82336, 109782],
  seo: { title: "حلقات تحفيظ القرآن أونلاين في الأرجنتين | حفظ ومراجعة بالعربية", description: "حفظ ومراجعة القرآن أونلاين في الأرجنتين، مع حلقات فردية باللغة العربية ومسار لتأسيس الحروف والقراءة والكتابة. اطّلع على الباقات الحالية بالبيزو الأرجنتيني واطلب الحصة التجريبية.", canonical: "https://quran-elhafez.com/argentina" },
  keywords: ["حفظ القرآن أونلاين في الأرجنتين", "مراجعة القرآن بالعربية في بوينس آيرس في الأرجنتين", "تلاوة القرآن وتجويده أونلاين في الأرجنتين", "حلقات تحفيظ القرآن الفردية في الأرجنتين", "تحفيظ القرآن للصغار والكبار في الأرجنتين", "تأسيس الحروف العربية والقراءة في قرطبة في الأرجنتين"],
  localCard: { title: "ARGENTINA · AL-HAFIZ ACADEMY", heading: "Memorización del Corán y bases del árabe online en Argentina", body: "Al-Hafiz Academy ofrece aprendizaje individual online para la memorización del Corán y las bases de la lengua árabe para estudiantes arabófonos en Argentina. Buenos Aires, Córdoba, Rosario y Mendoza son referencias geográficas de esta página. El aprendizaje es online y la comunicación con la academia se realiza en árabe. La academia no tiene oficina, sucursal ni lugar de enseñanza local en Argentina." },
  faq: [["كيف تبدأ الدراسة من الأرجنتين؟", "تبدأ الدراسة أونلاين بذكر الهدف والمستوى والوقت المناسب، ثم تُرتب الحصة التجريبية المجانية."], ["هل الأسعار بالبيزو الأرجنتيني؟", "نعم، الأسعار الظاهرة في صفحة الأرجنتين بالبيزو الأرجنتيني."], ["ما مدة الحصة الأساسية؟", "مدة الحصة الأساسية المعروضة 30 دقيقة."], ["بأي لغة يتم التواصل؟", "يتم التواصل مع الأكاديمية باللغة العربية."], ["هل توجد باقات مخصصة؟", "يوجد باقات مخصصة."]] as const,
} as const
export const argentinaWhatsApp = "https://bit.ly/4aJfOl6"
