export type CountryEducationalContent = {
  name: string
  localTitle: string
  localDescription: string
  quranTitle: string
  quranBody: string
  arabicTitle: string
  arabicBody: string
  quranArticleTitle: string
  quranArticleBody: string
  arabicArticleTitle: string
  arabicArticleBody: string
  teacherAngle: string
}

const sharedTeacherLine = "يعمل المعلمون والمعلمات بإجازات قرآنية معتمدة وموثقة وخبرة طويلة في تعليم القرآن وتأسيس العربية، وساعدوا طلابًا كثيرين على حفظ أجزاء كبيرة ومراجعتها."

export const countryEducationalContent: Record<string, CountryEducationalContent> = {
  "south-africa": { name: "جنوب أفريقيا", localTitle: "Aanlyn Koran- en Arabiese lesse in Suid-Afrika", localDescription: "Al-Hafiz Akademie bied individuele aanlynlesse vir Koranmemorisering en Arabiese grondslag aan Arabies-sprekende leerders. Die lesse en onderrig word in Arabies aangebied.", quranTitle: "مسار الحفظ والمراجعة", quranBody: "يبدأ الطالب من مستواه الحالي، ثم تتحول الحصة إلى وقت واضح للقراءة والحفظ والتسميع والمراجعة ضمن روتين يناسب الأسرة.", arabicTitle: "مسار تأسيس العربية", arabicBody: "يبني الطالب أساس القراءة والفهم بالعربية خطوةً خطوة، مع حصة فردية تركز على المهارة التي يحتاج إليها الآن.", quranArticleTitle: "كيف يحافظ الطالب على مراجعة القرآن؟", quranArticleBody: "تنجح المراجعة عندما تصبح جزءًا ثابتًا من الأسبوع. يبدأ الطالب بمقدار يناسب مستواه، يقرأه، يسمّعه، ثم يعود إلى المواضع التي تحتاج إلى تثبيت.", arabicArticleTitle: "من أين تبدأ القراءة العربية؟", arabicArticleBody: "تبدأ القراءة العربية من معرفة مستوى الطالب، ثم ترتيب الحروف والكلمات والجمل في خطوات قصيرة متتابعة.", teacherAngle: sharedTeacherLine },
  china: { name: "الصين", localTitle: "中国的古兰经与阿拉伯语在线课程", localDescription: "Al-Hafiz Academy 为阿拉伯语学习者提供古兰经背诵和阿拉伯语基础的一对一在线课程。课程与教学交流使用阿拉伯语。", quranTitle: "خطوة الحفظ من المنزل", quranBody: "حصة فردية منظمة تساعد الطالب على القراءة والحفظ والتسميع والمراجعة، وتربط الهدف الأسبوعي بالوقت المتاح في المنزل.", arabicTitle: "بداية واضحة للعربية", arabicBody: "مسار فردي لتأسيس القراءة والفهم بالعربية، يبدأ من مستوى الطالب ويصعد معه تدريجيًا.", quranArticleTitle: "لماذا تحتاج المراجعة إلى إيقاع ثابت؟", quranArticleBody: "الإيقاع الثابت يجعل الحفظ قابلًا للمتابعة؛ فكل حصة تجمع بين الجديد وما سبق حفظه بطريقة تناسب مستوى الطالب.", arabicArticleTitle: "أساس القراءة قبل سرعة التقدم", arabicArticleBody: "عندما يتأسس الطالب في الحروف والكلمات والنطق، يصبح الانتقال إلى القراءة والفهم أكثر وضوحًا وتنظيمًا.", teacherAngle: sharedTeacherLine },
  russia: { name: "روسيا", localTitle: "Онлайн-занятия Кораном и арабским языком в России", localDescription: "Al-Hafiz Academy проводит индивидуальные онлайн-занятия по заучиванию Корана и основам арабского языка для арабоговорящих учащихся. Обучение проходит на арабском языке.", quranTitle: "خريطة الحفظ", quranBody: "يتحرك الطالب بين القراءة والحفظ والتسميع والمراجعة في حصة فردية ذات خطوات واضحة، مع مراعاة مستواه وهدفه.", arabicTitle: "أساس عربي قابل للبناء", arabicBody: "تدريب فردي يضع أساسًا للقراءة والفهم والنطق بالعربية بطريقة تناسب بداية الطالب.", quranArticleTitle: "الحفظ والمراجعة كمسارين متصلين", quranArticleBody: "لا ينفصل الحفظ عن المراجعة؛ كل جديد يحتاج إلى عودة منظمة حتى يتحول إلى معرفة ثابتة في الذاكرة.", arabicArticleTitle: "القراءة العربية بين التدرج والفهم", arabicArticleBody: "يحتاج الطالب إلى تدرج يجمع بين التعرف إلى الكلمات وقراءتها وفهم معناها في سياق بسيط.", teacherAngle: sharedTeacherLine },
  norway: { name: "النرويج", localTitle: "Nettundervisning i Koranen og arabisk i Norge", localDescription: "Al-Hafiz Academy tilbyr individuelle nettleksjoner i koranmemorering og arabisk for arabisktalende elever. Undervisningen og den pedagogiske kommunikasjonen foregår på arabisk.", quranTitle: "روتين يناسب الأسبوع", quranBody: "يساعد المسار الفردي على توزيع الحفظ والتسميع والمراجعة في وقت عملي يناسب الأسرة والطالب.", arabicTitle: "العربية من الأساس", arabicBody: "تأسيس تدريجي للقراءة والفهم والنطق، مع توجيه مباشر داخل الحصة الفردية.", quranArticleTitle: "كيف يصنع الطالب وقتًا للمراجعة؟", quranArticleBody: "اختيار موعد ثابت ومقدار قابل للاستمرار يمنح المراجعة مكانًا واضحًا داخل الأسبوع.", arabicArticleTitle: "خطوات هادئة لبناء القراءة", arabicArticleBody: "تتقدم القراءة حين يتدرب الطالب على مهارة واحدة في كل مرة، ثم يربطها بكلمات وجمل مفهومة.", teacherAngle: sharedTeacherLine },
  italy: { name: "إيطاليا", localTitle: "Lezioni online di Corano e arabo in Italia", localDescription: "Al-Hafiz Academy offre lezioni individuali online per la memorizzazione del Corano e le basi dell'arabo agli studenti di lingua araba. Le lezioni e la comunicazione didattica si svolgono in arabo.", quranTitle: "حفظ يتقدم مع المراجعة", quranBody: "مسار فردي يوازن بين القراءة والحفظ والتسميع وتصحيح التلاوة، بحيث يعرف الطالب ما الذي يراجعه في كل حصة.", arabicTitle: "تأسيس العربية للقراءة والفهم", arabicBody: "دروس فردية تضع أساسًا متدرجًا للقراءة والفهم بالعربية بحسب بداية الطالب وهدفه.", quranArticleTitle: "من الحفظ الجديد إلى التثبيت", quranArticleBody: "كل مقطع جديد يحتاج إلى عودة قريبة ثم مراجعات متباعدة؛ هذه الحركة تمنح الطالب طريقة واضحة للاستمرار.", arabicArticleTitle: "لماذا يبدأ تأسيس العربية من المستوى؟", arabicArticleBody: "تحديد مستوى الطالب يمنع القفز بين مهارات متفرقة، ويجعل القراءة والنطق والفهم تسير في ترتيب مفهوم.", teacherAngle: sharedTeacherLine },
  austria: { name: "النمسا", localTitle: "Online-Koran- und Arabischunterricht in Österreich", localDescription: "Die Al-Hafiz Academy bietet individuelle Online-Unterrichtsstunden zum Auswendiglernen des Korans und für Arabisch-Grundlagen für arabischsprachige Lernende. Unterricht und pädagogische Kommunikation erfolgen auf Arabisch.", quranTitle: "نظام واضح للحفظ", quranBody: "يستند المسار إلى قراءة وتسميع ومراجعة متتابعة، مع وقت فردي يساعد الطالب على فهم خطوته التالية.", arabicTitle: "العربية عبر أساس متدرج", arabicBody: "يبني الطالب مهارات القراءة والفهم والنطق من نقطة بداية واضحة وبإيقاع مناسب.", quranArticleTitle: "كيف تخدم المراجعة جودة الحفظ؟", quranArticleBody: "المراجعة تكشف المواضع التي تحتاج إلى تثبيت، وتمنح الطالب فرصة لتصحيح القراءة قبل إضافة مقدار جديد.", arabicArticleTitle: "تأسيس العربية ليس حفظ كلمات فقط", arabicArticleBody: "يجمع التأسيس بين معرفة الكلمة وقراءتها ونطقها وفهمها، حتى تتحول المهارة إلى استخدام حقيقي.", teacherAngle: sharedTeacherLine },
  switzerland: { name: "سويسرا", localTitle: "Cours en ligne de Coran et d'arabe en Suisse", localDescription: "Al-Hafiz Academy propose des cours individuels en ligne de mémorisation du Coran et de bases de l'arabe pour les apprenants arabophones. Les cours et la communication pédagogique se font en arabe.", quranTitle: "مساحة للحفظ الهادئ", quranBody: "حصة فردية تمنح الطالب مساحة للقراءة والتسميع والمراجعة دون ازدحام، وتربط كل أسبوع بهدف قابل للمتابعة.", arabicTitle: "بداية عربية منظمة", arabicBody: "مسار لتأسيس القراءة والفهم والنطق بالعربية مع شرح مباشر يناسب مستوى الطالب.", quranArticleTitle: "وقت قليل مع مراجعة ذكية", quranArticleBody: "لا يحتاج الطالب إلى ملء يومه؛ يحتاج إلى مقدار منتظم وعودة واعية إلى ما حفظه سابقًا.", arabicArticleTitle: "القراءة والفهم في مسار واحد", arabicArticleBody: "تتطور القراءة عندما يتعلم الطالب نطق الكلمات وربطها بمعناها داخل جملة واضحة.", teacherAngle: sharedTeacherLine },
  brazil: { name: "البرازيل", localTitle: "Aulas online de Alcorão e árabe no Brasil", localDescription: "A Al-Hafiz Academy oferece aulas individuais online de memorização do Alcorão e fundamentos do árabe para estudantes arabófonos. As aulas e a comunicação educacional são em árabe.", quranTitle: "طريق قرآني فردي", quranBody: "يتلقى الطالب توجيهًا مباشرًا في الحفظ والتسميع والمراجعة، مع تقسيم المسار إلى خطوات مناسبة للوقت والهدف.", arabicTitle: "العربية بأساس عملي", arabicBody: "تدريب تدريجي على القراءة والفهم والنطق بالعربية، مع حصة فردية تركز على احتياج الطالب.", quranArticleTitle: "الحفظ عادة قبل أن يكون قائمة", quranArticleBody: "تثبيت موعد للمراجعة وتحويله إلى عادة أسبوعية يساعد الطالب على الاستمرار بوضوح.", arabicArticleTitle: "كيف يصبح الحرف كلمة؟", arabicArticleBody: "يبني الطالب القراءة من الحروف إلى الكلمات ثم الجمل، مع تكرار يربط النطق بالمعنى.", teacherAngle: sharedTeacherLine },
  mexico: { name: "المكسيك", localTitle: "Clases online de Corán y árabe en México", localDescription: "Al-Hafiz Academy ofrece clases individuales online para memorizar el Corán y aprender las bases del árabe para estudiantes arabófonos. Las clases y la comunicación educativa son en árabe.", quranTitle: "فصول صغيرة للحفظ", quranBody: "يُقسم الطالب طريقه إلى قراءة وحفظ وتسميع ومراجعة، حتى تكون كل حصة مركزة وسهلة المتابعة.", arabicTitle: "فصل البداية العربية", arabicBody: "تأسيس فردي للقراءة والفهم يبدأ من المستوى الحقيقي للطالب ولا يفترض معرفة سابقة.", quranArticleTitle: "المقطع الصغير يصنع تقدمًا ثابتًا", quranArticleBody: "تقسيم الحفظ إلى مقاطع قابلة للإنجاز يجعل المراجعة أوضح ويمنح الطالب إحساسًا مستمرًا بالتقدم.", arabicArticleTitle: "من الحروف إلى الجملة", arabicArticleBody: "تتدرج العربية من التعرف إلى الحرف إلى قراءة كلمة ثم جملة مع فهم معناها.", teacherAngle: sharedTeacherLine },
  colombia: { name: "كولومبيا", localTitle: "Clases virtuales de Corán y árabe en Colombia", localDescription: "Al-Hafiz Academy ofrece clases individuales virtuales de memorización del Corán y fundamentos del árabe para estudiantes arabófonos. La enseñanza y la comunicación educativa son en árabe.", quranTitle: "إجابة عن حاجة الطالب", quranBody: "يبدأ المسار من سؤال عملي: ماذا يحتاج الطالب أن يحفظ أو يراجع الآن؟ ثم تُبنى الحصة حول الإجابة.", arabicTitle: "إجابة تأسيسية بالعربية", arabicBody: "تدريب فردي يجيب عن صعوبة القراءة أو الفهم بخطوات مرتبة ومباشرة.", quranArticleTitle: "السؤال الصحيح يفتح باب المراجعة", quranArticleBody: "تحديد الموضع الصعب يجعل المراجعة أكثر تركيزًا من تكرار مقدار كبير بلا هدف واضح.", arabicArticleTitle: "ما المهارة العربية الأولى؟", arabicArticleBody: "تختلف البداية من طالب إلى آخر؛ لذلك يبدأ التأسيس من القراءة أو النطق أو الفهم بحسب الحاجة.", teacherAngle: sharedTeacherLine },
  venezuela: { name: "فنزويلا", localTitle: "Clases online de Corán y árabe en Venezuela", localDescription: "Al-Hafiz Academy ofrece clases individuales online para la memorización del Corán y las bases del árabe a estudiantes arabófonos. Las clases y la comunicación educativa se realizan en árabe.", quranTitle: "صورة واضحة لروتين الحفظ", quranBody: "يرى الطالب داخل الحصة ما سيقرأه ويحفظه ويسمّعه ويراجعه، فيتحول الطريق إلى خطوات مرئية.", arabicTitle: "صورة البداية في العربية", arabicBody: "مسار عملي يوضح للطالب مهارة القراءة أو الفهم التي يعمل عليها في كل مرحلة.", quranArticleTitle: "لماذا نراجع قبل أن نضيف؟", quranArticleBody: "العودة إلى السابق تكشف قوة الحفظ وتمنح المقطع الجديد أساسًا أقوى.", arabicArticleTitle: "الفهم رفيق القراءة", arabicArticleBody: "قراءة العربية لا تكتمل بالنطق وحده؛ يرتبط التقدم بفهم الكلمات والجمل تدريجيًا.", teacherAngle: sharedTeacherLine },
  denmark: { name: "الدنمارك", localTitle: "Online Koran- og arabisktimer i Danmark", localDescription: "Al-Hafiz Academy tilbyder individuelle onlinelektioner i Koran-memorering og arabisk for arabisktalende elever. Undervisning og pædagogisk kommunikation foregår på arabisk.", quranTitle: "مهمة أسبوعية للقرآن", quranBody: "يخرج الطالب من الحصة بمهمة واضحة للحفظ أو المراجعة، تساعده على تنظيم وقته بين الحصص.", arabicTitle: "مهمة عربية قابلة للإنجاز", arabicBody: "تُرتب القراءة والفهم والنطق في مهام قصيرة تتناسب مع مستوى الطالب.", quranArticleTitle: "المراجعة تحتاج إلى موعد", quranArticleBody: "عندما تُحجز المراجعة داخل الجدول، يصبح الحفاظ على المحفوظ أسهل من تركه للوقت المتبقي.", arabicArticleTitle: "تنظيم مهارات القراءة", arabicArticleBody: "تجتمع القراءة والكتابة والنطق في خطة واحدة، لكن كل مهارة تأخذ وقتها المناسب.", teacherAngle: sharedTeacherLine },
  greece: { name: "اليونان", localTitle: "Διαδικτυακά μαθήματα Κορανίου και αραβικών στην Ελλάδα", localDescription: "Η Al-Hafiz Academy προσφέρει ατομικά διαδικτυακά μαθήματα απομνημόνευσης του Κορανίου και βασικών αραβικών για αραβόφωνους μαθητές. Η διδασκαλία γίνεται στα αραβικά.", quranTitle: "مراحل متتابعة للحفظ", quranBody: "يتدرج الطالب من القراءة إلى الحفظ ثم التسميع والمراجعة، مع انتقال واضح من مرحلة إلى أخرى.", arabicTitle: "مراحل تأسيس العربية", arabicBody: "يبدأ الطالب من مهارته الحالية ويتقدم في القراءة والفهم والنطق ضمن مسار فردي.", quranArticleTitle: "كل مرحلة لها وظيفة", quranArticleBody: "القراءة تهيئ، والحفظ يثبت، والتسميع يكشف، والمراجعة تحافظ؛ اجتماعها يصنع روتينًا متوازنًا.", arabicArticleTitle: "التدرج يجعل العربية مفهومة", arabicArticleBody: "يحتاج الطالب إلى ترتيب واضح حتى لا تختلط عليه الحروف والكلمات والقواعد والفهم.", teacherAngle: sharedTeacherLine },
  "new-zealand": { name: "نيوزيلندا", localTitle: "Akoranga Koran me te reo Arapi ā-ipurangi i Aotearoa", localDescription: "Ka whakarato a Al-Hafiz Academy i ngā akoranga ā-ipurangi takitahi mō te maumahara Koran me ngā pūtake o te reo Arapi mō ngā ākonga kōrero Arapi. Ka whakahaerehia ngā akoranga i te reo Arapi.", quranTitle: "مساران يلتقيان في الهدف", quranBody: "يجتمع الحفظ والمراجعة في خطة فردية تضع الهدف والوقت ومستوى الطالب في صورة واحدة.", arabicTitle: "مسار عربي يرافق الأسرة", arabicBody: "تأسيس القراءة والفهم بالعربية في حصة تناسب إيقاع الطالب واحتياجه.", quranArticleTitle: "الهدف الواضح يخفف التشتت", quranArticleBody: "عندما يعرف الطالب مقدار ما يراجعه وما يضيفه، يصبح الأسبوع أكثر تنظيمًا.", arabicArticleTitle: "كيف نربط القراءة بالفهم؟", arabicArticleBody: "يُقرأ النص القصير، ثم تُشرح كلماته، ثم يستخدم الطالب ما تعلمه في جملة مفهومة.", teacherAngle: sharedTeacherLine },
  finland: { name: "فنلندا", localTitle: "Koraanin ja arabian verkkotunteja Suomessa", localDescription: "Al-Hafiz Academy tarjoaa arabiaa puhuville oppijoille yksilöllisiä verkkotunteja Koraanin ulkoa opetteluun ja arabian perusteisiin. Opetus ja koulutuksellinen viestintä tapahtuvat arabiaksi.", quranTitle: "مساحة تركيز للحفظ", quranBody: "حصة هادئة تركز على مقدار محدد من القراءة والحفظ والتسميع والمراجعة دون تشتيت.", arabicTitle: "تأسيس عربي بلا ازدحام", arabicBody: "يبني الطالب أساس القراءة والفهم تدريجيًا، مع اختيار مهارة واضحة لكل حصة.", quranArticleTitle: "الهدوء يساعد على تثبيت المحفوظ", quranArticleBody: "تقليل المهام داخل الحصة يتيح للطالب أن ينتبه إلى القراءة والتسميع وتصحيح المواضع الصعبة.", arabicArticleTitle: "الأساس الواضح يسبق السرعة", arabicArticleBody: "تحتاج العربية إلى أساس مرتب في القراءة والنطق قبل الانتقال إلى نصوص أطول.", teacherAngle: sharedTeacherLine },
  turkey: { name: "تركيا", localTitle: "Türkiye'de çevrim içi Kur'an ve Arapça dersleri", localDescription: "Al-Hafiz Academy, Arapça konuşan öğrenciler için Kur'an ezberi ve Arapça temelleri üzerine birebir çevrim içi dersler sunar. Dersler ve eğitim iletişimi Arapça yapılır.", quranTitle: "تبويب واضح للحفظ", quranBody: "يختار الطالب داخل المسار ما يحتاج إليه من قراءة وحفظ وتسميع ومراجعة، ثم يبدأ بخطوة واضحة.", arabicTitle: "تبويب تأسيس العربية", arabicBody: "دروس فردية للقراءة والفهم والنطق، مرتبة من المستوى الحالي إلى المهارة التالية.", quranArticleTitle: "الحفظ يحتاج إلى عودة منظمة", quranArticleBody: "المراجعة ليست مرحلة لاحقة فقط؛ هي عودة مستمرة إلى المحفوظ مع كل تقدم جديد.", arabicArticleTitle: "القراءة العربية رحلة قصيرة الخطوات", arabicArticleBody: "تكرار الحرف والكلمة والجملة في سياق مفهوم يساعد الطالب على بناء قراءة مستقرة.", teacherAngle: sharedTeacherLine },
  indonesia: { name: "إندونيسيا", localTitle: "Kelas online Al-Qur'an dan bahasa Arab di Indonesia", localDescription: "Al-Hafiz Academy menyediakan kelas online privat untuk menghafal Al-Qur'an dan dasar bahasa Arab bagi pelajar berbahasa Arab. Pengajaran dan komunikasi pendidikan dilakukan dalam bahasa Arab.", quranTitle: "محطات جزيرة الحفظ", quranBody: "ينتقل الطالب بين محطات القراءة والحفظ والتسميع والمراجعة، وكل محطة لها هدف صغير يمكن متابعته.", arabicTitle: "محطات تأسيس العربية", arabicBody: "يبدأ الطالب من مهارته الحالية ويتقدم بين القراءة والفهم والنطق بمحطات متدرجة.", quranArticleTitle: "قسّم الطريق إلى محطات", quranArticleBody: "تقسيم الحفظ إلى محطات يجعل الطالب يعرف موضعه وما تبقى له من العمل.", arabicArticleTitle: "كلمة مفهومة أفضل من قائمة طويلة", arabicArticleBody: "تساعد الكلمة داخل جملة على الجمع بين القراءة والنطق والفهم في تدريب واحد.", teacherAngle: sharedTeacherLine },
  malaysia: { name: "ماليزيا", localTitle: "Kelas Al-Quran dan bahasa Arab dalam talian di Malaysia", localDescription: "Al-Hafiz Academy menyediakan kelas dalam talian secara individu untuk hafazan Al-Quran dan asas bahasa Arab kepada pelajar berbahasa Arab. Pengajaran dijalankan dalam bahasa Arab.", quranTitle: "ملاحظات عملية للحفظ", quranBody: "يتابع الطالب ملاحظات الحصة في القراءة والحفظ والتسميع والمراجعة، ثم يعود إليها في الأسبوع.", arabicTitle: "ملاحظات تأسيسية للعربية", arabicBody: "توضح الحصة المهارة العربية التي يعمل عليها الطالب والطريقة المناسبة لتثبيتها.", quranArticleTitle: "دوّن ما يحتاج إلى مراجعة", quranArticleBody: "ملاحظة المواضع المتعثرة تحول المراجعة من تكرار عام إلى عمل محدد.", arabicArticleTitle: "التأسيس يتقدم بالملاحظة", arabicArticleBody: "معرفة نوع الصعوبة في القراءة تساعد على اختيار التدريب الأقرب إلى احتياج الطالب.", teacherAngle: sharedTeacherLine },
  portugal: { name: "البرتغال", localTitle: "Aulas online de Alcorão e árabe em Portugal", localDescription: "A Al-Hafiz Academy oferece aulas individuais online de memorização do Alcorão e fundamentos de árabe para estudantes arabófonos. O ensino e a comunicação educativa são em árabe.", quranTitle: "رحلة الحفظ خطوة خطوة", quranBody: "تربط الحصة بين هدف الطالب ومقدار الحفظ والمراجعة، ليعرف المسار إلى أين يتجه.", arabicTitle: "رحلة تأسيس العربية", arabicBody: "ينتقل الطالب في القراءة والفهم والنطق من خطوة إلى التي تليها داخل حصة فردية.", quranArticleTitle: "كل رحلة تحتاج إلى علامات طريق", quranArticleBody: "تسجيل ما تم حفظه وما يحتاج إلى مراجعة يجعل الرحلة التعليمية أكثر وضوحًا.", arabicArticleTitle: "من قراءة النص إلى فهمه", arabicArticleBody: "يبدأ الفهم من كلمات واضحة، ثم يتسع إلى جمل ونصوص قصيرة مناسبة للمستوى.", teacherAngle: sharedTeacherLine },
  poland: { name: "بولندا", localTitle: "Internetowe lekcje Koranu i arabskiego w Polsce", localDescription: "Al-Hafiz Academy prowadzi indywidualne lekcje online zapamiętywania Koranu i podstaw języka arabskiego dla osób arabskojęzycznych. Nauka i komunikacja edukacyjna odbywają się po arabsku.", quranTitle: "حلول عملية للمراجعة", quranBody: "يضع الطالب مع المعلم نقطة واضحة للعمل عليها: قراءة، حفظ، تسميع أو مراجعة، ثم يواصل من هناك.", arabicTitle: "حل مشكلة بداية العربية", arabicBody: "يحدد الطالب المهارة التي تعوقه، ثم يتدرب عليها تدريجيًا حتى تصبح أساسًا للخطوة التالية.", quranArticleTitle: "ما الحل عندما يتشتت الحفظ؟", quranArticleBody: "تقليل مقدار الجديد وزيادة المراجعة لفترة قصيرة يساعدان على استعادة وضوح المسار.", arabicArticleTitle: "كيف نتجاوز صعوبة البداية؟", arabicArticleBody: "تحديد الحرف أو الكلمة أو النطق الذي يحتاج إلى تدريب يجعل البداية قابلة للإنجاز.", teacherAngle: sharedTeacherLine },
  argentina: { name: "الأرجنتين", localTitle: "Clases online de Corán y árabe en Argentina", localDescription: "Al-Hafiz Academy ofrece clases individuales online para memorizar el Corán y aprender las bases del árabe a estudiantes arabófonos. La enseñanza y la comunicación educativa son en árabe.", quranTitle: "إيقاعان للحفظ والمراجعة", quranBody: "يوازن الطالب بين إضافة مقدار جديد والعودة إلى المحفوظ، فيصبح لكل أسبوع إيقاع مفهوم.", arabicTitle: "إيقاع القراءة والفهم", arabicBody: "تتقدم العربية عبر تدريب منتظم على القراءة والنطق والفهم داخل حصة فردية.", quranArticleTitle: "المراجعة تحفظ إيقاع الطريق", quranArticleBody: "لا يقاس التقدم بالجديد وحده؛ فالمحفوظ السابق يحتاج إلى وقت حتى يبقى حاضرًا.", arabicArticleTitle: "التعلم المنتظم يصنع فرقًا", arabicArticleBody: "جلسات قصيرة ومنظمة تساعد الطالب على تحويل القراءة إلى عادة يمكن الحفاظ عليها.", teacherAngle: sharedTeacherLine },
  senegal: { name: "السنغال", localTitle: "Cours en ligne de Coran et d'arabe au Sénégal", localDescription: "Al-Hafiz Academy propose des cours individuels en ligne de mémorisation du Coran et de bases de l'arabe pour les apprenants arabophones. L'enseignement se fait en arabe.", quranTitle: "شرائط مترابطة للحفظ", quranBody: "يرتبط الجديد بالمراجعة والتسميع في مسار فردي، بحيث يعرف الطالب كيف ينتقل من شريط إلى آخر.", arabicTitle: "شريط تأسيس العربية", arabicBody: "تتصل القراءة بالنطق والفهم في خطوات متدرجة تناسب بداية الطالب.", quranArticleTitle: "المراجعة شريط لا ينقطع", quranArticleBody: "كل عودة إلى المحفوظ تقوي الصلة به، وتساعد الطالب على مواصلة الجديد بثبات.", arabicArticleTitle: "العربية تبنى طبقة بعد طبقة", arabicArticleBody: "يضيف الطالب مهارة جديدة بعد أن يثبت ما قبلها، فيصبح التعلم متصلًا لا متقطعًا.", teacherAngle: sharedTeacherLine },
  nigeria: { name: "نيجيريا", localTitle: "Darussan Al-Qur'ani da Larabci ta yanar gizo a Najeriya", localDescription: "Al-Hafiz Academy tana ba da darussa na mutum ɗaya ta yanar gizo don haddar Al-Qur'ani da tushen Larabci ga masu magana da Larabci. Ana koyarwa da sadarwa ta ilimi cikin Larabci.", quranTitle: "قائمة تشغيل قرآنية", quranBody: "يتابع الطالب حلقات واضحة في القراءة والحفظ والتسميع والمراجعة، وكل حصة تضيف خطوة إلى القائمة.", arabicTitle: "قائمة خطوات عربية", arabicBody: "يرتب الطالب مهارات القراءة والفهم والنطق في خطوات قصيرة يراجعها داخل الحصة.", quranArticleTitle: "اجعل للمراجعة قائمة واضحة", quranArticleBody: "كتابة ما سيُراجع قبل الحصة تساعد الطالب على دخولها بهدف محدد بدل التشتت بين مواضع كثيرة.", arabicArticleTitle: "الخطوة الأولى في القراءة", arabicArticleBody: "تبدأ القراءة العربية من مهارة واحدة واضحة، ثم تضاف إليها الكلمات والجمل مع الفهم.", teacherAngle: sharedTeacherLine },
}

const legacyNames: Record<string, string> = {
  "united-states": "الولايات المتحدة", "united-kingdom": "المملكة المتحدة", "united-arab-emirates": "الإمارات", "saudi-arabia": "السعودية", germany: "ألمانيا", australia: "أستراليا", canada: "كندا", france: "فرنسا", spain: "إسبانيا", sweden: "السويد", netherlands: "هولندا", belgium: "بلجيكا", qatar: "قطر", kuwait: "الكويت", oman: "عُمان", bahrain: "البحرين", jordan: "الأردن",
}

for (const [slug, name] of Object.entries(legacyNames)) {
  if (countryEducationalContent[slug]) continue
  countryEducationalContent[slug] = {
    name,
    localTitle: `Online Quran and Arabic lessons in ${name}`,
    localDescription: `Al-Hafiz Academy provides individual online Quran memorization and Arabic foundation lessons for Arabic-speaking learners in ${name}. Lessons and educational communication are delivered in Arabic.`,
    quranTitle: `خدمة القرآن في ${name}`,
    quranBody: `حصص فردية للحفظ والتسميع والمراجعة للناطقين بالعربية في ${name}، تبدأ من مستوى الطالب وهدفه ووقته المتاح.`,
    arabicTitle: `خدمة العربية في ${name}`,
    arabicBody: `تأسيس فردي للقراءة والفهم والنطق بالعربية، مع مسار يناسب مستوى الطالب والأسرة في ${name}.`,
    quranArticleTitle: `روتين عملي لمراجعة القرآن في ${name}`,
    quranArticleBody: "تحتاج المراجعة إلى مقدار ثابت وموعد واضح وعودة منتظمة إلى المحفوظ، حتى يظل التعلم جزءًا من الأسبوع.",
    arabicArticleTitle: `بداية منظمة لتعلم العربية في ${name}`,
    arabicArticleBody: "تبدأ العربية من تحديد المستوى، ثم تدريب متدرج يجمع القراءة والنطق والفهم في خطوات قصيرة.",
    teacherAngle: sharedTeacherLine,
  }
}

const legacyLocalCards: Record<string, Pick<CountryEducationalContent, "localTitle" | "localDescription">> = {
  germany: { localTitle: "Online-Koran- und Arabischunterricht in Deutschland", localDescription: "Die Al-Hafiz Academy bietet individuellen Online-Unterricht zum Auswendiglernen des Korans und für Arabisch-Grundlagen für arabischsprachige Lernende. Unterricht und pädagogische Kommunikation erfolgen auf Arabisch." },
  france: { localTitle: "Cours en ligne de Coran et d'arabe en France", localDescription: "Al-Hafiz Academy propose des cours individuels en ligne de mémorisation du Coran et de bases de l'arabe pour les apprenants arabophones. Les cours et la communication pédagogique se font en arabe." },
  spain: { localTitle: "Clases online de Corán y árabe en España", localDescription: "Al-Hafiz Academy ofrece clases individuales online para la memorización del Corán y las bases del árabe a estudiantes arabófonos. Las clases y la comunicación educativa se realizan en árabe." },
  sweden: { localTitle: "Onlinekurser i Koranen och arabiska i Sverige", localDescription: "Al-Hafiz Academy erbjuder individuella onlinelektioner i koranmemorisering och arabiska för arabisktalande elever. Undervisning och pedagogisk kommunikation sker på arabiska." },
  netherlands: { localTitle: "Online lessen in de Koran en Arabisch in Nederland", localDescription: "Al-Hafiz Academy biedt individuele online lessen in het memoriseren van de Koran en de basis van het Arabisch voor Arabischsprekende leerlingen. De lessen en educatieve communicatie zijn in het Arabisch." },
  belgium: { localTitle: "Cours en ligne de Coran et d'arabe en Belgique", localDescription: "Al-Hafiz Academy propose des cours individuels en ligne de mémorisation du Coran et de bases de l'arabe pour les apprenants arabophones. L'enseignement et la communication pédagogique se font en arabe." },
}

for (const [slug, localCard] of Object.entries(legacyLocalCards)) {
  countryEducationalContent[slug] = { ...countryEducationalContent[slug], ...localCard }
}
