export const GERMANY_WHATSAPP_NUMBER = "201130127894"
export type GermanyProgram = "quran" | "arabic"
export type GermanyDuration = 30
export type GermanySessions = 4 | 8 | 12 | 16
export interface GermanyPlan { id: string; program: GermanyProgram; duration: GermanyDuration; monthlySessions: GermanySessions; weeklySessions: 1 | 2 | 3 | 4; price: number; name: string; description: string; features: string[]; popular?: boolean }
const schedule = [[4, 1], [8, 2], [12, 3], [16, 4]] as const
const quranPrices = { 30: [15, 25, 40, 50] } as const
const arabicPrices = { 30: [20, 30, 45, 60] } as const
function makePlans(program: GermanyProgram, prices: Record<GermanyDuration, readonly number[]>) { return ([30] as const).flatMap((duration) => schedule.map(([monthlySessions, weeklySessions], index) => ({ id: `${program}-${duration}-${monthlySessions}`, program, duration, monthlySessions, weeklySessions, price: prices[duration][index], name: `${program === "quran" ? "تحفيظ القرآن" : "تأسيس اللغة العربية"} — ${duration} دقيقة — ${monthlySessions} حصص شهرياً`, description: program === "quran" ? "حصة فردية مباشرة للحفظ والتسميع وتصحيح التلاوة والمراجعة." : "حصة فردية مباشرة لتأسيس القراءة والكتابة والنطق والفهم بالعربية.", features: program === "quran" ? ["معلمون ومعلمات حسب المتاح", "خطة حفظ ومراجعة", "موعد مرن بتوقيت ألمانيا"] : ["قراءة وكتابة ونطق", "متابعة تناسب مستوى الطالب", "بيئة مناسبة للأطفال والأسرة"], popular: monthlySessions === 8 }))) }
export const germanyLandingConfig = { whatsappNumber: GERMANY_WHATSAPP_NUMBER, seo: { title: "تحفيظ القرآن وتأسيس اللغة العربية أونلاين للعرب في ألمانيا | حصة مجانية", description: "حصص فردية أونلاين لتحفيظ القرآن وتأسيس اللغة العربية للأطفال والشباب والبالغين من الناطقين بالعربية في برلين وميونخ وفرانكفورت وهامبورغ وباقي مدن ألمانيا، مع أول حصة تجريبية مجانية ومواعيد مرنة وخصم خاص للأخوة.", canonical: "https://quran-elhafez.com/germany" }, cities: ["برلين", "هامبورغ", "ميونخ", "فرانكفورت", "كولونيا", "دوسلدورف", "شتوتغارت", "هانوفر", "بريمن", "دورتموند", "لايبزيغ", "نورمبرغ"], plans: [...makePlans("quran", quranPrices), ...makePlans("arabic", arabicPrices)] satisfies GermanyPlan[] } as const
export function getGermanyWhatsAppUrl(plan?: GermanyPlan) { const message = plan ? `السلام عليكم،\nأرغب في الاشتراك في باقة ${plan.program === "quran" ? "تحفيظ القرآن" : "تأسيس اللغة العربية"} — ${plan.duration} دقيقة للحصة — ${plan.monthlySessions} حصص شهرياً — بقيمة €${plan.price} باليورو في ألمانيا.\n\nبيانات الطالب:\nالاسم:\nالعمر:\nولد أم بنت:\nالمستوى الحالي أو كمية الحفظ:\nمعلم أم معلمة:\nالمدينة داخل ألمانيا:\nالوقت المناسب للحصة التجريبية:\nهل يوجد إخوة آخرون للاستفادة من خصم الأخوة؟` : `السلام عليكم،\nأرغب في حجز أول حصة تجريبية مجانية في تحفيظ القرآن أو تأسيس اللغة العربية للناطقين بالعربية في ألمانيا.\n\nبيانات الطالب:\nالاسم:\nالعمر:\nولد أم بنت:\nقرآن أم تأسيس عربي:\nالمستوى الحالي أو كمية الحفظ:\nمعلم أم معلمة:\nالمدينة داخل ألمانيا:\nالوقت المناسب للحصة التجريبية:`; return `https://wa.me/${GERMANY_WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}` }
export const germanyFaq = [["هل تناسب الحصص الأطفال المقيمين في ألمانيا؟", "نعم، الحصص الفردية مناسبة للأطفال والشباب والبالغين، مع خطة ومدة تناسب العمر والمستوى."], ["كيف نختار الموعد المناسب مع فرق التوقيت؟", "ننسق مع الأسرة حسب توقيت ألمانيا والموعد المتاح للطالب والمعلم أو المعلمة."], ["هل أول حصة تجريبية مجانية؟", "نعم، أول حصة تجريبية مجانية للتعرف على مستوى الطالب واحتياجه قبل اختيار الباقة."], ["هل يوجد خصم للأخوة؟", "نعم، يوجد خصم خاص للأخوة، وتُعرف التفاصيل عند التواصل عبر WhatsApp."], ["هل يمكن اختيار معلم أو معلمة؟", "يمكن ذكر التفضيل عند الحجز، وسننسق حسب التوفر والبرنامج المناسب."], ["هل يبدأ الطالب من الصفر في تحفيظ القرآن؟", "نعم، نبدأ من المستوى الحالي للطالب مع خطة للحفظ والتسميع والمراجعة وتصحيح التلاوة عند توفره."], ["هل يبدأ الطالب من الحروف في تأسيس اللغة العربية؟", "نعم، يمكن البدء من الحروف أو تقييم المستوى والانتقال إلى القراءة والكتابة والنطق."], ["هل تشمل حصة العربية القراءة والكتابة والنطق؟", "نعم، يحدد البرنامج المهارات المطلوبة ويجمع بينها تدريجياً وفق مستوى الطالب."], ["هل يمكن تقييم مستوى الطالب قبل اختيار الباقة؟", "نعم، نقيّم المستوى خلال الحصة التجريبية ونقترح المدة والإيقاع الأنسب."], ["هل الأسعار شهرية وباليورو؟", "نعم، الأسعار المعروضة شهرية وباليورو، وتختلف حسب مدة الحصة وعدد الحصص."], ["كيف يتم الحجز والتواصل عبر WhatsApp؟", "اضغط زر الحجز، وأرسل البيانات المطلوبة، وسيتواصل معك الفريق لتنسيق الموعد."]] as const
