export const indonesiaLandingConfig = {
  slug: "indonesia", name: "إندونيسيا", nameEn: "Indonesia", flag: "🇮🇩", currencyCode: "IDR", currencySymbol: "Rp",
  cities: ["جاكرتا", "سورابايا", "باندونغ", "ميدان"], timezone: "توقيت غرب إندونيسيا (Asia/Jakarta)",
  quranPrices: [268800, 501760, 752640, 985600], arabicPrices: [358400, 645120, 967680, 1290240],
  seo: { title: "تحفيظ القرآن وتأسيس العربية أونلاين في إندونيسيا | حلقات فردية", description: "توفر الصفحة مسارًا لحفظ القرآن ومراجعته ومسارًا لتأسيس العربية من الحروف إلى القراءة والكتابة، في حلقات فردية أونلاين من إندونيسيا. راجع الأسعار بالروبية الإندونيسية واطلب الحصة التجريبية.", canonical: "https://quran-elhafez.com/indonesia" },
  keywords: ['حفظ القرآن أونلاين في إندونيسيا', 'مراجعة القرآن بالعربية في جاكرتا في إندونيسيا', 'تلاوة القرآن وتجويده أونلاين في إندونيسيا', 'حلقات تحفيظ القرآن الفردية في إندونيسيا', 'تحفيظ القرآن للصغار والكبار في إندونيسيا', 'تأسيس الحروف العربية والقراءة في سورابايا في إندونيسيا'],
  localCard: { title: "INDONESIA · AL-HAFIZ ACADEMY", heading: "Hafalan Al-Qur’an dan dasar bahasa Arab secara online di Indonesia", body: "Al-Hafiz Academy menyediakan pembelajaran online secara individual untuk hafalan Al-Qur’an dan dasar bahasa Arab bagi pelajar berbahasa Arab di Indonesia. Jakarta, Surabaya, Bandung, dan Medan menjadi konteks geografis halaman ini. Pembelajaran berlangsung online dan komunikasi dengan akademi dilakukan dalam bahasa Arab. Akademi tidak memiliki kantor, cabang, atau tempat belajar lokal di Indonesia." },
  faq: [["كيف تبدأ الدراسة من إندونيسيا؟", "تبدأ الدراسة أونلاين بذكر الهدف والمستوى والوقت المناسب، ثم تُرتب الحصة التجريبية المجانية."], ["هل الأسعار بالروبية الإندونيسية؟", "نعم، الأسعار الظاهرة في صفحة إندونيسيا بالروبية الإندونيسية."], ["ما مدة الحصة الأساسية؟", "مدة الحصة الأساسية المعروضة 30 دقيقة."], ["بأي لغة يتم التواصل؟", "يتم التواصل مع الأكاديمية باللغة العربية."], ["هل توجد باقات مخصصة؟", "يوجد باقات مخصصة."]] as const,
} as const
export const indonesiaWhatsApp = "https://wa.me/message/62LK42KU3LCCM1"
