export const malaysiaLandingConfig = {
  slug: "malaysia", name: "ماليزيا", nameEn: "Malaysia", flag: "🇲🇾", currencyCode: "MYR", currencySymbol: "RM",
  cities: ["كوالالمبور", "جورج تاون", "جوهور باهرو", "كوتا كينابالو"], timezone: "توقيت ماليزيا (Asia/Kuala_Lumpur)",
  quranPrices: [61, 114, 171, 224], arabicPrices: [81, 146, 219, 293],
  seo: { title: "تحفيظ القرآن للصغار والكبار أونلاين في ماليزيا | فردي", description: "تحفيظ القرآن متاح للصغار والكبار في حلقات فردية أونلاين من ماليزيا. اختر هدف الحفظ أو المراجعة، واسأل عن الباقات المعروضة بالرينغيت الماليزي ومسار تأسيس الحروف والقراءة والكتابة.", canonical: "https://quran-elhafez.com/malaysia" },
  keywords: ['حفظ القرآن أونلاين في ماليزيا', 'مراجعة القرآن بالعربية في كوالالمبور في ماليزيا', 'تلاوة القرآن وتجويده أونلاين في ماليزيا', 'حلقات تحفيظ القرآن الفردية في ماليزيا', 'تحفيظ القرآن للصغار والكبار في ماليزيا', 'تأسيس الحروف العربية والقراءة في جورج تاون في ماليزيا'],
  localCard: { title: "MALAYSIA · AL-HAFIZ ACADEMY", heading: "Hafazan al-Quran dan asas bahasa Arab secara dalam talian di Malaysia", body: "Al-Hafiz Academy menyediakan pembelajaran dalam talian secara individu untuk hafazan al-Quran dan asas bahasa Arab bagi pelajar berbahasa Arab di Malaysia. Kuala Lumpur, George Town, Johor Bahru dan Kota Kinabalu ialah konteks geografi halaman ini. Pembelajaran berlangsung dalam talian dan komunikasi dengan akademi dilakukan dalam bahasa Arab. Akademi tidak mempunyai pejabat, cawangan atau tempat belajar tempatan di Malaysia." },
  faq: [["كيف تبدأ الدراسة من ماليزيا؟", "تبدأ الدراسة أونلاين بذكر الهدف والمستوى والوقت المناسب، ثم تُرتب الحصة التجريبية المجانية."], ["هل الأسعار بالرينغيت الماليزي؟", "نعم، الأسعار الظاهرة في صفحة ماليزيا بالرينغيت الماليزي."], ["ما مدة الحصة الأساسية؟", "مدة الحصة الأساسية المعروضة 30 دقيقة."], ["بأي لغة يتم التواصل؟", "يتم التواصل مع الأكاديمية باللغة العربية."], ["هل توجد باقات مخصصة؟", "يوجد باقات مخصصة."]] as const,
} as const
export const malaysiaWhatsApp = "https://bit.ly/4aJfOl6"
