export const senegalLandingConfig = {
  slug: "senegal", name: "السنغال", nameEn: "Senegal", flag: "🇸🇳", currencyCode: "XOF", currencySymbol: "XOF",
  cities: ["داكار", "تييس", "سانت لويس", "زيغينشور"], timezone: "توقيت السنغال (Africa/Dakar)",
  quranPrices: [8637, 16122, 24183, 31668], arabicPrices: [11516, 20728, 31093, 41457],
  seo: { title: "حفظ ومراجعة القرآن أونلاين في السنغال | متابعة بعد الحلقة", description: "تعلم القرآن أونلاين من السنغال بحلقات فردية بالعربية. بعد كل حصة تقرير متابعة يوضح الدرس والواجب ورقم الحلقة والتاريخ وأسماء الطالب والمعلم؛ وتظهر الباقات بفرنك CFA لغرب أفريقيا.", canonical: "https://quran-elhafez.com/senegal" },
  keywords: ["حفظ القرآن أونلاين في السنغال", "مراجعة القرآن بالعربية في داكار في السنغال", "تلاوة القرآن وتجويده أونلاين في السنغال", "حلقات تحفيظ القرآن الفردية في السنغال", "تحفيظ القرآن للصغار والكبار في السنغال", "تأسيس الحروف العربية والقراءة في تييس في السنغال"],
  localCard: { title: "SÉNÉGAL · AL-HAFIZ ACADEMY", heading: "Mémorisation du Coran et bases de l’arabe en ligne au Sénégal", body: "Al-Hafiz Academy propose un apprentissage individuel en ligne pour la mémorisation du Coran et les bases de la langue arabe destinés aux apprenants arabophones au Sénégal. Dakar, Thiès, Saint-Louis et Ziguinchor sont des références géographiques de cette page. L’apprentissage est en ligne et la communication avec l’académie se fait en arabe. L’académie n’a pas de bureau, de succursale ni de lieu d’enseignement local au Sénégal." },
  faq: [["كيف تبدأ الدراسة من السنغال؟", "تبدأ الدراسة أونلاين بذكر الهدف والمستوى والوقت المناسب، ثم تُرتب الحصة التجريبية المجانية."], ["هل الأسعار بفرنك CFA؟", "نعم، الأسعار الظاهرة في صفحة السنغال بفرنك CFA لغرب أفريقيا."], ["ما مدة الحصة الأساسية؟", "مدة الحصة الأساسية المعروضة 30 دقيقة."], ["بأي لغة يتم التواصل؟", "يتم التواصل مع الأكاديمية باللغة العربية."], ["هل توجد باقات مخصصة؟", "يوجد باقات مخصصة."]] as const,
} as const
export const senegalWhatsApp = "https://wa.me/message/62LK42KU3LCCM1"
