export const venezuelaLandingConfig = {
  slug: "venezuela", name: "فنزويلا", nameEn: "Venezuela", flag: "🇻🇪", currencyCode: "VES", currencySymbol: "VES",
  cities: ["كاراكاس", "ماراكايبو", "فالنسيا", "باركيسيميتو"], timezone: "توقيت فنزويلا (America/Caracas، UTC−04:00)",
  quranPrices: [12839, 23966, 35949, 47076], arabicPrices: [17118, 30813, 46220, 61627],
  seo: { title: "حلقة قرآن أونلاين في فنزويلا | الحفظ والتلاوة بالعربية", description: "للطالب في فنزويلا، تتوفر حلقات فردية أونلاين لحفظ القرآن ومراجعته والتدرب على التلاوة. كما يشمل مسار العربية الحروف والقراءة والكتابة؛ وتظهر الأسعار بالبوليفار الفنزويلي.", canonical: "https://quran-elhafez.com/venezuela" },
  keywords: ['حفظ القرآن أونلاين في فنزويلا', 'مراجعة القرآن بالعربية في كاراكاس في فنزويلا', 'تلاوة القرآن وتجويده أونلاين في فنزويلا', 'حلقات تحفيظ القرآن الفردية في فنزويلا', 'تحفيظ القرآن للصغار والكبار في فنزويلا', 'تأسيس الحروف العربية والقراءة في ماراكايبو في فنزويلا'],
  localCard: { title: "VENEZUELA · AL-HAFIZ ACADEMY", heading: "Memorización del Corán y fundamentos del árabe en línea en Venezuela", body: "Al-Hafiz Academy ofrece clases individuales en línea para memorizar el Corán y aprender los fundamentos del árabe para estudiantes que hablan árabe en Venezuela. Caracas, Maracaibo, Valencia y Barquisimeto son referencias geográficas de esta página. Las clases son en línea y la comunicación con la academia se realiza en árabe. La academia no tiene sede, sucursal ni lugar de enseñanza en Venezuela." },
  faq: [["هل الدراسة أونلاين من فنزويلا؟", "نعم، الدراسة أونلاين، والمدن المذكورة سياق جغرافي للصفحة فقط دون مقرات أو فروع أو أماكن تدريس محلية."], ["هل الأسعار بالبوليفار الفنزويلي؟", "نعم، الأسعار الظاهرة في صفحة فنزويلا بالبوليفار الفنزويلي."], ["ما مدة الحصة الأساسية؟", "مدة الحصة الأساسية المعروضة 30 دقيقة."], ["بأي لغة يتم التواصل؟", "يتم التواصل مع الأكاديمية باللغة العربية."], ["هل توجد باقات مخصصة؟", "يوجد باقات مخصصة."]] as const,
} as const
export const venezuelaWhatsApp = "https://bit.ly/4aJfOl6"
