'use client'

import { useState } from "react"
import Image from "next/image"
import { Play } from "lucide-react"
import { VideoPlayer } from "@/components/VideoPlayer"
import type { LandingVideo } from "@/lib/classroom-videos"

export function MalaysiaSchoolVideo({ videos }: { videos: LandingVideo[] }) { const [selected, setSelected] = useState<LandingVideo | null>(null); const items = videos.filter((video) => video.showOnLandingPages).slice(0, 4); return <section className="bg-[#F3F4F6] px-5 py-20 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-black tracking-[0.28em] text-[#047857]">دفتر التعلم · أمثلة مرئية</p><h2 className="mt-4 text-4xl font-black text-[#1F2937] sm:text-6xl">اقرأ الفكرة ثم شاهد المثال</h2>{items.length ? <div className="mt-10 space-y-5">{items.map((video, i) => <button type="button" key={video.id} onClick={() => setSelected(video)} className="group flex w-full flex-col overflow-hidden rounded-md border-2 border-[#D1D5DB] bg-white text-right shadow-[6px_6px_0_#FDE68A] md:flex-row"><div className="relative h-56 shrink-0 bg-[#047857] md:h-48 md:w-80">{video.thumbnail_url ? <Image loader={({ src }) => src} src={video.thumbnail_url} alt={video.title_ar} fill sizes="320px" className="object-cover transition-transform duration-300 group-hover:scale-105 motion-reduce:transition-none" /> : null}<span className="absolute inset-0 grid place-items-center bg-[#047857]/25"><span className="grid size-14 place-items-center rounded-full bg-[#FDE68A] text-[#1F2937]"><Play size={22} fill="currentColor" /></span></span></div><div className="flex flex-1 flex-col justify-center p-7"><span className="text-xs font-black text-[#6D28D9]">ملاحظة مرئية {i + 1}</span><p className="mt-3 text-xl font-black text-[#1F2937]">{video.title_ar}</p><p className="mt-3 text-sm leading-7 text-[#1F2937]/65">مقطع تعريفي من محتوى الأكاديمية المنشور. اضغط لفتح المقطع.</p></div></button>)}</div> : <p className="mt-8 rounded-md border-2 border-[#D1D5DB] bg-white p-6 font-bold text-[#1F2937]">محتوى التعريف المرئي سيظهر من المواد المنشورة.</p>}{selected ? <VideoPlayer isOpen videoId={selected.youtube_embed_id} title={selected.title_ar} onClose={() => setSelected(null)} /> : null}</div></section> }
