'use client'

import { useState } from "react"
import { ChevronDown, MessageCircle } from "lucide-react"

export function NewZealandFoldingPlans({ quranPrices, arabicPrices, whatsapp }: { quranPrices: readonly number[]; arabicPrices: readonly number[]; whatsapp: string }) {
  const [program, setProgram] = useState<"quran" | "arabic">("quran")
  const prices = program === "quran" ? quranPrices : arabicPrices
  const label = program === "quran" ? "تحفيظ القرآن الكريم" : "تأسيس اللغة العربية"
  return <section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><p className="font-black text-[#1F5D50]">نقطة الالتقاء · اختيار البرنامج</p><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={() => setProgram("quran")} className={`rounded-full px-6 py-3 font-black ${program === "quran" ? "bg-[#1F5D50] text-white" : "bg-[#E9D8B4] text-[#163C3A]"}`}>تحفيظ القرآن</button><button type="button" onClick={() => setProgram("arabic")} className={`rounded-full px-6 py-3 font-black ${program === "arabic" ? "bg-[#185A7A] text-white" : "bg-[#E9D8B4] text-[#163C3A]"}`}>تأسيس العربية</button></div><h2 className="mt-8 text-4xl font-black text-[#163C3A]">{label}</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{prices.map((price, index) => <details key={price} className="group rounded-[1.5rem] border-2 border-[#1F5D50]/30 bg-[#FBFAF5] p-5 shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-4"><span><b className="block text-xl">{index + 1}. باقة {index === 0 ? "البداية" : index === 1 ? "الاستمرار" : index === 2 ? "التقدم" : "التركيز"}</b><small className="mt-1 block">{(index + 1) * 4} حصص شهريًا · 30 دقيقة للحصة</small></span><span className="flex items-center gap-3"><strong className="text-3xl text-[#185A7A]">{price} NZ$</strong><ChevronDown className="transition group-open:rotate-180" /></span></summary><div className="mt-5 border-t border-[#1F5D50]/20 pt-4"><p className="leading-8">خطة فردية تناسب تكرار {index + 1} {index === 0 ? "مرة أسبوعيًا" : index === 1 ? "مرتين أسبوعيًا" : index === 2 ? "ثلاث مرات أسبوعيًا" : "أربع مرات أسبوعيًا"}.</p><a href={`${whatsapp}?text=${encodeURIComponent(`أرغب في الاستفسار عن ${label} وباقة ${price} دولار نيوزيلندي`)}`} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#1F5D50] px-5 py-3 font-black text-white"><MessageCircle size={17} /> اسأل عن الباقة</a></div></details>)}</div><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full bg-[#1F5D50] px-5 py-3 font-black text-white">يوجد باقات مخصصة.</span><span className="rounded-full bg-[#E9D8B4] px-5 py-3 font-black text-[#163C3A]">خصم 10٪ للأخوات والإحالة</span></div></div></section>
}
