'use client'

import { useState } from "react"
import Image from "next/image"
import { ListVideo, Play } from "lucide-react"
import { VideoPlayer } from "@/components/VideoPlayer"
import type { LandingVideo } from "@/lib/classroom-videos"

export function NigeriaPlaylistVideo({ videos }: { videos: LandingVideo[] }) { const [selected, setSelected] = useState<LandingVideo | null>(null); const items = videos.filter((video) => video.showOnLandingPages).slice(0, 4); return <section className="bg-white px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-center gap-3"><ListVideo className="text-[#F97316]" size={28} /><div><p className="text-xs font-black tracking-[0.24em] text-[#F97316]">قائمة المشاهدة · 02</p><h2 className="mt-2 text-3xl font-black text-[#064E3B]">اختر مقطعًا من قائمة المشاهدة</h2></div></div>{items.length ? <div className="mt-8 divide-y divide-[#D1D5DB] rounded-2xl border border-[#D1D5DB] bg-[#F3F4F6]">{items.map((video, i) => <button type="button" key={video.id} onClick={() => setSelected(video)} className="flex w-full items-center gap-4 p-4 text-right"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#064E3B] font-black text-white">{String(i + 1).padStart(2, "0")}</span><span className="relative size-20 shrink-0 overflow-hidden rounded-lg bg-[#064E3B]">{video.thumbnail_url ? <Image loader={({ src }) => src} src={video.thumbnail_url} alt={video.title_ar} fill sizes="80px" loading="lazy" className="object-cover" /> : null}<span className="absolute inset-0 grid place-items-center bg-[#064E3B]/45"><Play size={18} fill="currentColor" className="text-white" /></span></span><span className="min-w-0 flex-1"><b className="block truncate text-[#064E3B]">{video.title_ar}</b><span className="mt-1 block text-xs text-[#111827]/55">مقطع {i + 1} · مشاهدة عند الضغط</span></span></button>)}</div> : <p className="mt-8 rounded-xl bg-[#F3F4F6] p-6 text-[#111827]/70">محتوى التعريف المرئي سيظهر من المواد المنشورة.</p>}{selected ? <VideoPlayer isOpen videoId={selected.youtube_embed_id} title={selected.title_ar} onClose={() => setSelected(null)} /> : null}</div></section> }
