"use client"

import { useMemo, useState } from "react"
import { Eye, EyeOff, Save, Plus, Trash2 } from "lucide-react"
import { uaeLandingConfig, type UaePlan } from "@/lib/uae-landing-config"

type UaeAdminConfig = {
  visible: boolean
  whatsappNumber: string
  seo: { title: string; description: string; canonical: string }
  cities: string[]
  whatsappTemplate: string
  plans: UaePlan[]
}

export function UaeLandingTab() {
  const [config, setConfig] = useState<UaeAdminConfig>(() => ({ ...uaeLandingConfig, cities: [...uaeLandingConfig.cities], plans: [...uaeLandingConfig.plans] }))
  const [status, setStatus] = useState("")
  const [filter, setFilter] = useState<"all" | "quran" | "arabic">("all")
  const plans = useMemo(() => config.plans.filter((plan) => filter === "all" || plan.program === filter), [config.plans, filter])
  const updatePlan = (id: string, patch: Partial<UaePlan>) => setConfig((current) => ({ ...current, plans: current.plans.map((plan) => plan.id === id ? { ...plan, ...patch } : plan) }))
  const addPlan = () => setConfig((current) => ({ ...current, plans: [...current.plans, { id: `draft-${Date.now()}`, program: "quran", duration: 30, monthlySessions: 4, weeklySessions: 1, price: 0, name: "باقة جديدة", description: "وصف الباقة", features: ["ميزة جديدة"], popular: false, order: current.plans.length + 1, visible: true }] }))
  const removePlan = (id: string) => setConfig((current) => ({ ...current, plans: current.plans.filter((plan) => plan.id !== id) }))
  const saveDraft = () => setStatus("تم حفظ التعديلات محلياً كمسودة. الربط الدائم مع Supabase مؤجل كما هو مطلوب.")

  return <div className="space-y-6" dir="rtl">
    <div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">صفحة الهبوط الإماراتية</h2><p className="mt-2 text-sm text-muted-foreground">إدارة منظمة للبيانات قبل ربطها بمصدر دائم مثل Supabase.</p></div><button type="button" onClick={saveDraft} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 font-bold text-primary-foreground"><Save size={17} /> حفظ مسودة</button></div>{status && <p className="mt-4 rounded-lg bg-secondary p-3 text-sm text-secondary-foreground" role="status">{status}</p>}</div>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h3 className="text-lg font-bold">الإعدادات العامة</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">عنوان SEO<input value={config.seo.title} onChange={(event) => setConfig((current) => ({ ...current, seo: { ...current.seo, title: event.target.value } }))} className="rounded-lg border border-border bg-background p-3 font-normal" /></label><label className="grid gap-2 text-sm font-semibold">رقم واتساب<input value={config.whatsappNumber} readOnly className="rounded-lg border border-border bg-muted p-3 font-normal" /></label><label className="grid gap-2 text-sm font-semibold md:col-span-2">الوصف التعريفي<textarea value={config.seo.description} onChange={(event) => setConfig((current) => ({ ...current, seo: { ...current.seo, description: event.target.value } }))} className="min-h-24 rounded-lg border border-border bg-background p-3 font-normal" /></label><label className="grid gap-2 text-sm font-semibold md:col-span-2">قالب رسالة واتساب<textarea value={config.whatsappTemplate} readOnly className="min-h-40 rounded-lg border border-border bg-muted p-3 font-mono text-xs font-normal" /></label></div><div className="mt-5 flex flex-wrap gap-2">{config.cities.map((city) => <span key={city} className="rounded-full bg-secondary px-3 py-1 text-xs font-semibold">{city}</span>)}<span className="rounded-full bg-secondary px-3 py-1 text-xs font-semibold">جميع مدن الإمارات</span></div></section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">إدارة الباقات</h3><p className="mt-1 text-sm text-muted-foreground">إضافة وتعديل وحذف وترتيب المسودات دون ادعاء حفظ دائم.</p></div><button type="button" onClick={addPlan} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-bold"><Plus size={16} /> إضافة باقة</button></div><div className="mt-5 flex gap-2"><select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)} className="rounded-lg border border-border bg-background p-2 text-sm"><option value="all">كل البرامج</option><option value="quran">قرآن</option><option value="arabic">عربي</option></select></div><div className="mt-5 grid gap-4">{plans.map((plan) => <div key={plan.id} className="rounded-xl border border-border p-4"><div className="grid gap-3 md:grid-cols-6"><input aria-label="اسم الباقة" value={plan.name} onChange={(event) => updatePlan(plan.id, { name: event.target.value })} className="rounded-lg border border-border bg-background p-2 md:col-span-2" /><select aria-label="البرنامج" value={plan.program} onChange={(event) => updatePlan(plan.id, { program: event.target.value as UaePlan["program"] })} className="rounded-lg border border-border bg-background p-2"><option value="quran">قرآن</option><option value="arabic">عربي</option></select><select aria-label="مدة الحصة" value={plan.duration} onChange={(event) => updatePlan(plan.id, { duration: Number(event.target.value) as UaePlan["duration"] })} className="rounded-lg border border-border bg-background p-2"><option value="30">30 دقيقة</option></select><input aria-label="السعر بالدرهم الإماراتي" type="number" value={plan.price} onChange={(event) => updatePlan(plan.id, { price: Number(event.target.value) })} className="rounded-lg border border-border bg-background p-2" /><button type="button" aria-label={`حذف ${plan.name}`} onClick={() => removePlan(plan.id)} className="inline-flex items-center justify-center rounded-lg border border-destructive/30 p-2 text-destructive"><Trash2 size={17} /></button></div><div className="mt-3 flex flex-wrap items-center gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={plan.popular} onChange={(event) => updatePlan(plan.id, { popular: event.target.checked })} /> الأكثر طلباً</label><button type="button" onClick={() => updatePlan(plan.id, { visible: !plan.visible })} className="inline-flex items-center gap-2 text-muted-foreground">{plan.visible ? <Eye size={16} /> : <EyeOff size={16} />} {plan.visible ? "ظاهر" : "مخفي"}</button><span className="text-muted-foreground">{plan.monthlySessions} حصص شهرياً · {plan.price} ريال شهرياً</span></div></div>)}</div></section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h3 className="text-lg font-bold">إدارة الأقسام</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">نص قسم المدن<textarea defaultValue="نقدم الحصص أونلاين للطلاب والطالبات من جميع مدن الإمارات." className="min-h-24 rounded-lg border border-border bg-background p-3 font-normal" /></label><label className="grid gap-2 text-sm font-semibold">نص الدعوة النهائية<textarea defaultValue="ابدأ الآن بحصة تجريبية مجانية" className="min-h-24 rounded-lg border border-border bg-background p-3 font-normal" /></label></div><p className="mt-4 text-xs text-muted-foreground">الأسئلة الشائعة وخطوات البدء وروابط التذييل معرفة حالياً في typed config ويمكن نقلها إلى Supabase لاحقاً.</p></section>
  </div>
}
