import type { Metadata } from "next"
import type { CSSProperties } from "react"
import Link from "next/link"
import { Clock3, MapPin, MessageCircle } from "lucide-react"
import { getAreaLandingData, getAreaLinkHref, getAreaWhatsAppUrl, toAreaDisplayPlan } from "@/lib/country-content"
import { getPublishedClassroomVideos } from "@/lib/classroom-videos"
import { countryPages } from "@/components/layout/country-pages-section"
import { russiaLandingConfig, getRussiaWhatsAppUrl } from "@/lib/russia-landing-config"
import { RussiaVideoRibbon } from "./russia-video-ribbon"
import { RussiaPriceRibbon } from "./russia-price-ribbon"

const canonical = russiaLandingConfig.seo.canonical

export const metadata: Metadata = {
  title: russiaLandingConfig.seo.title,
  description: russiaLandingConfig.seo.description,
  keywords: ["تحفيظ القرآن أونلاين في روسيا", "تحفيظ القرآن في موسكو", "تحفيظ القرآن في سانت بطرسبرغ", "تعليم العربية أونلاين في روسيا", "دروس قرآن في قازان", "تعلم العربية في نوفوسيبيرسك", "باقات تحفيظ القرآن بالروبل"],
  alternates: { canonical, languages: { ar: canonical, "x-default": canonical } },
  openGraph: { title: russiaLandingConfig.seo.title, description: russiaLandingConfig.seo.description, url: canonical, locale: "ar_RU", type: "website", images: [{ url: "https://quran-elhafez.com/images/og-default.webp", width: 1200, height: 630, alt: "أكاديمية الحافظ المتميز في روسيا" }] },
  twitter: { card: "summary_large_image", title: russiaLandingConfig.seo.title, description: russiaLandingConfig.seo.description, images: ["https://quran-elhafez.com/images/og-default.webp"] },
}

export default async function RussiaPage() {
  const [areaData, videos] = await Promise.all([getAreaLandingData("russia"), getPublishedClassroomVideos()])
  const quranPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "quran")
  const arabicPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "arabic")
  const quranPrices = quranPlans.length >= 4 ? quranPlans.slice(0, 4).map((plan) => plan.price) : russiaLandingConfig.quranPrices
  const arabicPrices = arabicPlans.length >= 4 ? arabicPlans.slice(0, 4).map((plan) => plan.price) : russiaLandingConfig.arabicPrices
  const cities = areaData.cities.length ? areaData.cities.map((city) => city.name_ar) : russiaLandingConfig.cities
  const faq = areaData.faq.length ? areaData.faq.map((item) => [item.question_ar, item.answer_ar] as const) : russiaLandingConfig.faq
  const theme = areaData.theme ? { primary: areaData.theme.primary_color, accent: areaData.theme.accent_color, background: areaData.theme.background_color, surface: areaData.theme.secondary_color, ink: areaData.theme.text_color } : russiaLandingConfig.theme
  const baseContact = getAreaLinkHref(areaData.links, "whatsapp", getRussiaWhatsAppUrl())
  const trialUrl = getAreaWhatsAppUrl(areaData.links, "حصة تجريبية مجانية في روسيا", baseContact)
  const packageUrl = getAreaWhatsAppUrl(areaData.links, "باقات القرآن أو العربية في روسيا", baseContact)
  const jsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      { "@type": "WebPage", "@id": `${canonical}#webpage`, url: canonical, name: russiaLandingConfig.seo.title, description: russiaLandingConfig.seo.description, inLanguage: "ar" },
      { "@type": "EducationalOrganization", "@id": `${canonical}#organization`, name: "أكاديمية الحافظ المتميز", url: "https://quran-elhafez.com/", areaServed: { "@type": "Country", name: "Russia" } },
      { "@type": "Course", name: "تحفيظ القرآن أونلاين في روسيا", description: "حصص فردية للحفظ والمراجعة والقراءة عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: quranPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "RUB", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
      { "@type": "Course", name: "تأسيس العربية أونلاين في روسيا", description: "حصص فردية لبناء أساس القراءة والفهم بالعربية عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: arabicPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "RUB", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
      { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
    ],
  }

  return (
    <main dir="rtl" className="min-h-screen overflow-hidden" style={{ "--ru-primary": theme.primary, "--ru-accent": theme.accent, "--ru-background": theme.background, "--ru-surface": theme.surface, "--ru-ink": theme.ink } as CSSProperties}>
      <header className="bg-[#162B45] px-5 py-4 text-[#EAF4F7] sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><span className="font-black tracking-wide">روسيا · القرآن والعربية</span><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-md border border-[#B56B45] px-4 py-2 text-sm font-black text-[#EAF4F7]">احجز الحصة التجريبية</a></div></header>
      <section className="relative overflow-hidden bg-[#162B45] px-5 pb-20 pt-14 text-[#EAF4F7] sm:px-8 lg:pb-28 lg:pt-20"><div className="absolute -left-20 top-10 size-72 rounded-full border-[24px] border-[#31546D]/40" aria-hidden="true" /><div className="absolute bottom-0 right-1/3 h-1/2 w-px bg-[#C9D6DC]/20" aria-hidden="true" /><div className="relative mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div className="order-2 lg:order-1"><div className="grid grid-cols-2 gap-3 text-sm font-bold text-[#C9D6DC]"><span className="border-r-2 border-[#B56B45] pr-3">موسكو</span><span className="border-r-2 border-[#B56B45] pr-3">سانت بطرسبرغ</span><span className="border-r-2 border-[#B56B45] pr-3">قازان</span><span className="border-r-2 border-[#B56B45] pr-3">نوفوسيبيرسك</span></div><div className="mt-8 rounded-[2rem] border border-[#C9D6DC]/30 bg-[#31546D]/35 p-6"><p className="text-sm font-black text-[#B56B45]">روسيا · تعلم فردي أونلاين</p><p className="mt-3 text-2xl font-black leading-10">من البيت، ابدأ بخطوة واضحة وروتين قابل للاستمرار.</p><p className="mt-4 text-sm leading-7 text-[#EAF4F7]/75">الصفحة عربية، والتواصل مع الأكاديمية باللغة العربية.</p></div></div><div className="order-1 lg:order-2"><p className="text-sm font-black uppercase tracking-[0.28em] text-[#B56B45]">غلاف قطبي · روسيا</p><h1 className="mt-6 max-w-4xl text-balance text-5xl font-black leading-[1.08] sm:text-7xl">مساحة هادئة للقرآن وبداية منظمة للعربية</h1><p className="mt-7 max-w-2xl text-lg leading-9 text-[#EAF4F7]/85">من موسكو وسانت بطرسبرغ إلى قازان ونوفوسيبيرسك، ابدأ بتحديد هدفك ووقتك. تعرّف إلى البرنامج والباقات الشهرية، ثم تواصل معنا للحصة التجريبية.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#russia-plans" className="rounded-md bg-[#B56B45] px-6 py-3 font-black text-white">اعرف الباقات</a><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-md border border-[#EAF4F7] px-6 py-3 font-black">احجز الحصة التجريبية</a></div></div></div></section>
      <section lang="ru" className="bg-[#EAF4F7] px-5 py-12 sm:px-8" aria-labelledby="russia-local-card-title"><div className="mx-auto max-w-5xl rounded-[1.75rem] border-l-4 border-[#B56B45] bg-white p-6 text-left text-[#162B45] shadow-[8px_8px_0_#C9D6DC] sm:p-9"><p className="text-xs font-black tracking-[0.2em] text-[#B56B45]">{russiaLandingConfig.localCard.title}</p><h2 id="russia-local-card-title" className="mt-3 text-2xl font-black sm:text-3xl">{russiaLandingConfig.localCard.heading}</h2><p className="mt-4 max-w-4xl text-lg leading-8">{russiaLandingConfig.localCard.body}</p></div></section>
      <RussiaVideoRibbon videos={videos} />
      <section className="bg-white px-5 py-16 text-[#162B45] sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-black text-[#B56B45]">مساران واضحان</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">اختر نقطة البداية التعليمية</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-[2rem] border-r-8 border-[#B56B45] bg-[#EAF4F7] p-7"><p className="font-black text-[#31546D]">تحفيظ القرآن الكريم</p><h3 className="mt-3 text-3xl font-black">حفظ ومراجعة بإيقاع ثابت</h3><p className="mt-4 leading-8 text-[#162B45]/75">حصص فردية لتنظيم الحفظ والتسميع والمراجعة والقراءة وفق هدف الطالب، مع باقات شهرية واضحة بالروبل الروسي.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-md bg-[#162B45] px-5 py-3 font-black text-white">اسأل عن برنامج القرآن</a></article><article className="rounded-[2rem] border-r-8 border-[#31546D] bg-[#C9D6DC]/55 p-7"><p className="font-black text-[#B56B45]">تأسيس اللغة العربية</p><h3 className="mt-3 text-3xl font-black">أساس تدريجي للقراءة والفهم</h3><p className="mt-4 leading-8 text-[#162B45]/75">مسار فردي لبناء أساس القراءة والفهم بالعربية، يبدأ من مستوى الطالب وهدفه التعليمي.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-md border-2 border-[#162B45] px-5 py-3 font-black">اسأل عن برنامج العربية</a></article></div></div></section>
      <section className="bg-[#EAF4F7] px-5 py-16 text-[#162B45] sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-start gap-4"><MapPin className="mt-1 text-[#B56B45]" /><div><p className="text-sm font-black text-[#B56B45]">السياق المحلي</p><h2 className="mt-2 text-3xl font-black">التعلم أونلاين من مدن روسيا</h2><p className="mt-4 max-w-3xl leading-8 text-[#162B45]/75">يمكنك التعلم أونلاين من موسكو أو سانت بطرسبرغ أو قازان أو نوفوسيبيرسك. ذكر المدينة يوضح سياق الصفحة ولا يعني وجود فرع محلي.</p><div className="mt-6 flex flex-wrap gap-2">{cities.map((city) => <span key={city} className="rounded-md border border-[#31546D] bg-white px-4 py-2 text-sm font-bold">{city}</span>)}</div><p className="mt-5 flex items-center gap-2 text-sm font-bold text-[#31546D]"><Clock3 size={16} /> {areaData.timezones.find((timezone) => timezone.is_primary)?.label_ar || russiaLandingConfig.timezone}</p></div></div></div></section>
      <RussiaPriceRibbon whatsapp={packageUrl} quranPrices={quranPrices} arabicPrices={arabicPrices} />
      <section className="bg-[#162B45] px-5 py-16 text-[#EAF4F7] sm:px-8"><div className="mx-auto max-w-5xl"><p className="text-sm font-black text-[#B56B45]">فواصل الإجابة</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">أسئلة قبل بداية المسار</h2><div className="mt-8 space-y-3">{faq.map(([question, answer], index) => <article key={question} className="flex gap-4 border-b border-[#C9D6DC]/20 pb-5 pt-3"><span className="font-serif text-3xl text-[#B56B45]">{String(index + 1).padStart(2, "0")}</span><div><h3 className="font-black text-[#EAF4F7]">{question}</h3><p className="mt-2 leading-7 text-[#C9D6DC]">{answer}</p></div></article>)}</div></div></section>
      <section className="bg-[#B56B45] px-5 py-16 text-center text-white sm:px-8"><div className="mx-auto max-w-3xl"><h2 className="text-4xl font-black">ابدأ من هدف واضح</h2><p className="mt-4 leading-8">اذكر مدينتك والبرنامج الذي تريده والوقت المناسب لك، وسيتولى التواصل باللغة العربية تنسيق الخطوة التالية.</p><a href={trialUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-md bg-[#162B45] px-6 py-3 font-black"><MessageCircle size={18} /> أريد الحصة التجريبية</a></div></section>
      <footer className="border-t-4 border-[#C9D6DC] bg-[#162B45] px-5 py-7 text-[#EAF4F7] sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-black tracking-wide">روسيا · {new Date().getFullYear()}</span><nav aria-label="روابط صفحة روسيا" className="flex flex-wrap gap-x-5 gap-y-2 text-sm font-bold text-[#EAF4F7]/85"><Link href="/">الرئيسية</Link><Link href="/games">الألعاب والمسابقات</Link><Link href="/library">المكتبة</Link><Link href="/contact">التواصل</Link><Link href="/privacy">الخصوصية</Link><Link href="/terms">الشروط</Link></nav></div><details className="mt-6 border-t border-[#C9D6DC]/20 pt-5"><summary className="cursor-pointer text-sm font-black text-[#B56B45]">صفحاتنا حسب الدولة</summary><nav aria-label="كل صفحات الدول" className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{countryPages.map((country) => <Link key={country.href} href={country.href} className="rounded-md border border-[#C9D6DC]/20 px-3 py-2 text-sm text-[#EAF4F7]/85 transition hover:border-[#B56B45] hover:text-white"><span className="me-2" aria-hidden="true">{country.flag}</span>{country.label}</Link>)}</nav></details></div></footer>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    </main>
  )
}
