'use client'

import { useState } from "react"
import { BookOpen, MessageCircle } from "lucide-react"

export function MexicoChapterPricing({ whatsapp, quranPrices, arabicPrices }: { whatsapp: string; quranPrices: readonly number[]; arabicPrices: readonly number[] }) {
  const [program, setProgram] = useState<"quran" | "arabic">("quran")
  const prices = program === "quran" ? quranPrices : arabicPrices
  const title = program === "quran" ? "تحفيظ القرآن الكريم" : "تأسيس اللغة العربية"
  const plans = [{ sessions: 4, label: "الفصل الأول", rhythm: "مرة أسبوعيًا" }, { sessions: 8, label: "الفصل الثاني", rhythm: "مرتان أسبوعيًا" }, { sessions: 12, label: "الفصل الثالث", rhythm: "ثلاث مرات أسبوعيًا" }, { sessions: 16, label: "الفصل الرابع", rhythm: "أربع مرات أسبوعيًا" }]
  return <section id="mexico-pricing" className="bg-[#FFF7ED] px-5 py-16 text-[#241A2A] sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="flex items-center gap-2 text-sm font-black tracking-[0.2em] text-[#C2185B]"><BookOpen size={16} /> دفتر الباقات</p><h2 className="mt-3 text-4xl font-black sm:text-6xl">كل باقة فصل جديد</h2></div><div className="flex gap-2" role="tablist" aria-label="برامج المكسيك"><button type="button" role="tab" aria-selected={program === "quran"} onClick={() => setProgram("quran")} className={`rounded-t-2xl border-4 border-b-0 border-[#241A2A] px-5 py-3 font-black ${program === "quran" ? "bg-[#F08A24]" : "bg-white"}`}>القرآن</button><button type="button" role="tab" aria-selected={program === "arabic"} onClick={() => setProgram("arabic")} className={`rounded-t-2xl border-4 border-b-0 border-[#241A2A] px-5 py-3 font-black ${program === "arabic" ? "bg-[#C2185B] text-white" : "bg-white"}`}>العربية</button></div></div><p className="mt-5 max-w-2xl border-r-4 border-[#F08A24] pr-4 text-lg leading-8">{title} بحصة أساسية مدتها 30 دقيقة، بأسعار شهرية بالبيزو المكسيكي.</p><div className="mt-10 grid gap-6 md:grid-cols-2">{plans.map((plan, index) => <article key={plan.sessions} className={`relative rounded-[2rem] border-4 border-[#241A2A] p-7 shadow-[7px_7px_0_${index % 2 ? "#C2185B" : "#F08A24"}] ${index % 2 ? "bg-[#FDE4EF]" : "bg-white"}`}><span className="text-sm font-black text-[#243B80]">{plan.label}</span><h3 className="mt-3 text-2xl font-black">{plan.sessions} حصص شهريًا</h3><p className="mt-2 font-bold text-[#241A2A]/65">{plan.rhythm}</p><div className="mt-6 flex items-end justify-between gap-3"><strong className="text-4xl font-black text-[#C2185B]">MX${prices[index]}</strong><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-full bg-[#243B80] px-3 py-2 text-xs font-black text-white"><MessageCircle size={14} /> اسأل</a></div></article>)}</div><div className="mt-10 flex flex-wrap gap-3"><p className="rounded-xl bg-[#F08A24] px-5 py-3 font-black">يوجد باقات مخصصة.</p><p className="rounded-xl border-2 border-[#C2185B] px-5 py-3 font-black">خصم 10٪ للأخوات والإحالة</p></div></div></section>
}
