import type { Metadata } from "next"
import Link from "next/link"
import { Clock3, MapPin, MessageCircle, PenLine } from "lucide-react"
import { getAreaLandingData, getAreaLinkHref, getAreaWhatsAppUrl, toAreaDisplayPlan } from "@/lib/country-content"
import { getPublishedClassroomVideos } from "@/lib/classroom-videos"
import { countryPages } from "@/components/layout/country-pages-section"
import { mexicoLandingConfig, getMexicoWhatsAppUrl } from "@/lib/mexico-landing-config"
import { MexicoChapterPricing } from "./mexico-chapter-pricing"
import { MexicoStoryVideoRail } from "./mexico-story-video-rail"

const canonical = mexicoLandingConfig.seo.canonical
export const metadata: Metadata = {
  title: mexicoLandingConfig.seo.title, description: mexicoLandingConfig.seo.description,
  keywords: ["تحفيظ القرآن أونلاين في المكسيك", "تحفيظ القرآن في مدينة مكسيكو", "تحفيظ القرآن في غوادالاخارا", "تعليم العربية أونلاين في المكسيك", "دروس قرآن في مونتيري", "باقات تحفيظ القرآن بالبيزو المكسيكي"],
  alternates: { canonical, languages: { ar: canonical, "x-default": canonical } },
  openGraph: { title: mexicoLandingConfig.seo.title, description: mexicoLandingConfig.seo.description, url: canonical, locale: "ar_MX", type: "website", images: [{ url: "https://quran-elhafez.com/images/og-default.webp", width: 1200, height: 630, alt: "أكاديمية الحافظ المتميز في المكسيك" }] },
  twitter: { card: "summary_large_image", title: mexicoLandingConfig.seo.title, description: mexicoLandingConfig.seo.description, images: ["https://quran-elhafez.com/images/og-default.webp"] },
}

export default async function MexicoPage() {
  const [areaData, videos] = await Promise.all([getAreaLandingData("mexico"), getPublishedClassroomVideos()])
  const quranPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "quran")
  const arabicPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "arabic")
  const quranPrices = quranPlans.length >= 4 ? quranPlans.slice(0, 4).map((plan) => plan.price) : mexicoLandingConfig.quranPrices
  const arabicPrices = arabicPlans.length >= 4 ? arabicPlans.slice(0, 4).map((plan) => plan.price) : mexicoLandingConfig.arabicPrices
  const cities = areaData.cities.length ? areaData.cities.map((city) => city.name_ar) : mexicoLandingConfig.cities
  const faq = areaData.faq.length ? areaData.faq.map((item) => [item.question_ar, item.answer_ar] as const) : mexicoLandingConfig.faq
  const baseContact = getAreaLinkHref(areaData.links, "whatsapp", getMexicoWhatsAppUrl())
  const trialUrl = getAreaWhatsAppUrl(areaData.links, "حصة تجريبية مجانية في المكسيك", baseContact)
  const packageUrl = getAreaWhatsAppUrl(areaData.links, "باقات القرآن أو العربية في المكسيك", baseContact)
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "WebPage", "@id": `${canonical}#webpage`, url: canonical, name: mexicoLandingConfig.seo.title, description: mexicoLandingConfig.seo.description, inLanguage: "ar" },
    { "@type": "EducationalOrganization", "@id": `${canonical}#organization`, name: "أكاديمية الحافظ المتميز", url: "https://quran-elhafez.com/", areaServed: { "@type": "Country", name: "Mexico" } },
    { "@type": "Course", name: "تحفيظ القرآن أونلاين في المكسيك", description: "حصص فردية للحفظ والمراجعة والقراءة عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: quranPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "MXN", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "Course", name: "تأسيس العربية أونلاين في المكسيك", description: "حصص فردية لبناء أساس القراءة والفهم بالعربية عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: arabicPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "MXN", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  ] }
  return <main dir="rtl" className="min-h-screen overflow-hidden bg-[#FFF7ED] text-[#241A2A]"><header className="border-b-4 border-[#F08A24] bg-[#C2185B] px-5 py-4 text-white sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><span className="font-black">المكسيك · القرآن والعربية</span><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full bg-[#F08A24] px-4 py-2 text-sm font-black text-[#241A2A]">احجز الحصة التجريبية</a></div></header>
  <section className="px-5 py-12 sm:px-8"><div className="mx-auto max-w-6xl"><div className="relative overflow-hidden rounded-[3rem] border-4 border-[#241A2A] bg-[#F08A24] p-8 shadow-[14px_14px_0_#243B80] sm:p-14"><span className="absolute -left-8 -top-10 text-[14rem] font-black leading-none text-white/15">01</span><div className="relative max-w-3xl"><p className="flex items-center gap-2 text-sm font-black tracking-[0.2em] text-[#243B80]"><PenLine size={16} /> الفصل الأول · بداية واضحة</p><h1 className="mt-6 text-5xl font-black leading-[1.05] sm:text-7xl">اكتب بداية جديدة لتعلمك</h1><p className="mt-6 text-lg leading-9">من مدينة مكسيكو وغوادالاخارا إلى مونتيري وبويبلا، ابدأ تحفيظ القرآن أو تأسيس العربية بحصة فردية أونلاين. التواصل مع الأكاديمية باللغة العربية.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#mexico-pricing" className="rounded-full bg-[#243B80] px-6 py-3 font-black text-white">افتح دفتر الباقات</a><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full border-2 border-[#241A2A] px-6 py-3 font-black">احجز الحصة التجريبية</a></div></div></div></div></section>
  <section lang="es-MX" className="px-5 pb-14 sm:px-8" aria-labelledby="mexico-local-card-title"><div className="mx-auto max-w-6xl rounded-[2rem] border-4 border-[#241A2A] bg-white p-7 shadow-[8px_8px_0_#C2185B] sm:p-10"><p className="text-xs font-black tracking-[0.2em] text-[#C2185B]">{mexicoLandingConfig.localCard.title}</p><h2 id="mexico-local-card-title" className="mt-3 text-2xl font-black sm:text-3xl">{mexicoLandingConfig.localCard.heading}</h2><p className="mt-4 max-w-5xl text-lg leading-8">{mexicoLandingConfig.localCard.body}</p></div></section>
  <section className="bg-[#FFF7ED] px-5 py-10 sm:px-8"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-2"><article className="rounded-[2rem] border-4 border-[#243B80] bg-[#E8ECFF] p-8"><p className="font-black text-[#C2185B]">الفصل الثاني</p><h2 className="mt-3 text-3xl font-black">تحفيظ القرآن الكريم</h2><p className="mt-4 leading-8">روتين فردي للحفظ والتسميع والمراجعة والقراءة، يبدأ من مستوى الطالب وهدفه.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-[#243B80] px-5 py-3 font-black text-white">اسأل عن برنامج القرآن</a></article><article className="rounded-[2rem] border-4 border-[#C2185B] bg-[#FDE4EF] p-8"><p className="font-black text-[#243B80]">الفصل الثالث</p><h2 className="mt-3 text-3xl font-black">تأسيس اللغة العربية</h2><p className="mt-4 leading-8">مسار تدريجي لبناء أساس القراءة والفهم بالعربية من خلال حصص فردية أونلاين.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-[#C2185B] px-5 py-3 font-black text-white">اسأل عن برنامج العربية</a></article></div></section>
  <MexicoChapterPricing whatsapp={packageUrl} quranPrices={quranPrices} arabicPrices={arabicPrices} /><MexicoStoryVideoRail videos={videos} />
  <section className="bg-[#243B80] px-5 py-14 text-white sm:px-8"><div className="mx-auto flex max-w-6xl items-start gap-4"><MapPin className="mt-1 shrink-0 text-[#F08A24]" /><div><p className="text-sm font-black text-[#F08A24]">الفصل الجغرافي</p><h2 className="mt-2 text-3xl font-black">تعلم أونلاين من مدن المكسيك</h2><p className="mt-4 max-w-3xl leading-8 text-white/85">يمكنك التعلم أونلاين من مدينة مكسيكو أو غوادالاخارا أو مونتيري أو بويبلا. المدن سياق جغرافي للصفحة فقط، ولا توجد بها مقرات أو فروع أو أماكن تدريس تابعة للأكاديمية.</p><div className="mt-6 flex flex-wrap gap-2">{cities.map((city) => <span key={city} className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">{city}</span>)}</div><p className="mt-5 flex items-center gap-2 text-sm font-bold text-[#F08A24]"><Clock3 size={16} /> {areaData.timezones.find((timezone) => timezone.is_primary)?.label_ar || mexicoLandingConfig.timezone}</p></div></div></section>
  <section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-black text-[#C2185B]">الفصل الأخير · أسئلة القارئ</p><h2 className="mt-3 text-4xl font-black">افتح العنوان الذي يهمك</h2><div className="mt-8 space-y-4">{faq.map(([question, answer], index) => <details key={question} className="rounded-2xl border-4 border-[#241A2A] bg-white p-5 shadow-[5px_5px_0_#F08A24]"><summary className="cursor-pointer list-none font-black"><span className="me-3 text-[#C2185B]">الفصل 0{index + 1}</span>{question}</summary><p className="mt-4 border-t-2 border-[#241A2A]/10 pt-4 leading-7">{answer}</p></details>)}</div></div></section>
  <section className="bg-[#C2185B] px-5 py-16 text-center text-white sm:px-8"><div className="mx-auto max-w-3xl"><h2 className="text-4xl font-black">أكمل الفصل بسؤال واضح</h2><p className="mt-4 leading-8">اذكر مدينتك والبرنامج الذي تريده والوقت المناسب لك، وابدأ التواصل باللغة العربية.</p><a href={trialUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#F08A24] px-6 py-3 font-black text-[#241A2A]"><MessageCircle size={18} /> أريد الحصة التجريبية</a></div></section>
  <footer className="border-t-8 border-[#F08A24] bg-[#241A2A] px-5 py-8 text-white sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-black">المكسيك · {new Date().getFullYear()}</span><nav aria-label="روابط صفحة المكسيك" className="flex flex-wrap gap-x-5 gap-y-2 text-sm font-bold text-white/85"><Link href="/">الرئيسية</Link><Link href="/games">الألعاب والمسابقات</Link><Link href="/library">المكتبة</Link><Link href="/contact">التواصل</Link><Link href="/privacy">الخصوصية</Link><Link href="/terms">الشروط</Link></nav></div><details className="mt-6 border-t border-white/15 pt-5"><summary className="cursor-pointer text-sm font-black text-[#F08A24]">صفحاتنا حسب الدولة</summary><nav aria-label="كل صفحات الدول" className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{countryPages.map((country) => <Link key={country.href} href={country.href} className="rounded-md border border-white/15 px-3 py-2 text-sm text-white/85 transition hover:border-[#F08A24] hover:text-white"><span className="me-2" aria-hidden="true">{country.flag}</span>{country.label}</Link>)}</nav></details></div></footer><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></main>
}
