import { createClient } from "@supabase/supabase-js"

const blogPosts = [
  {
    slug: "quran-memorization-practical-guide",
    title_ar: "دليل عملي لبناء خطة ثابتة لحفظ القرآن ومراجعته",
    title_en: "A Practical Guide to Building a Consistent Quran Memorization Plan",
    title_fr: "Guide pratique pour construire un plan régulier de mémorisation du Coran",
    excerpt_ar: "خطة بسيطة تساعد الطالب والأسرة على تنظيم الحفظ والمراجعة والاستماع، مع الحفاظ على الاستمرارية دون ضغط زائد.",
    excerpt_en: "A simple plan for organizing memorization, revision, and listening while keeping steady progress without unnecessary pressure.",
    excerpt_fr: "Un plan simple pour organiser la mémorisation, la révision et l’écoute avec une progression régulière.",
    content_ar: `## البداية من هدف واضح\n\nنجاح خطة حفظ القرآن لا يعتمد على كثرة الصفحات وحدها، بل على وضوح الهدف والقدرة على الاستمرار. ابدأ بتحديد مقدار مناسب لأسبوعك، ثم اجعل للمراجعة وقتًا ثابتًا لا يقل أهمية عن وقت الحفظ الجديد.\n\n## خطوات عملية\n\n1. **قسّم المقطع إلى وحدات قصيرة:** اقرأ المقطع كاملًا لفهم سياقه، ثم قسّمه إلى آيات أو فقرات يسهل تكرارها.\n2. **استمع قبل التسميع:** اختر قارئًا مناسبًا واستمع إلى المقطع أكثر من مرة مع متابعة المصحف.\n3. **كرّر بطريقة متدرجة:** اقرأ من المصحف، ثم سمّع غيبًا، ثم ارجع إلى الموضع الذي أخطأت فيه فقط.\n4. **ثبّت المراجعة الأسبوعية:** خصص جلسة لمراجعة المحفوظ القديم قبل إضافة مقدار جديد.\n5. **سجّل التقدم بصدق:** سجل ما أُنجز وما يحتاج إلى إعادة، من غير مقارنة قاسية مع الآخرين.\n\n## دور الأسرة والمعلم\n\nالأسرة تساعد بتوفير وقت هادئ وتشجيع الطالب، بينما يساعد المعلم على تصحيح التلاوة، واكتشاف مواضع الضعف، وتعديل مقدار الحفظ بما يناسب المستوى والوقت.\n\n## خلاصة\n\nالخطة الناجحة هي التي يمكن الاستمرار عليها. القليل المنتظم مع مراجعة جيدة خير من خطة كبيرة تنقطع سريعًا. اجعل الحفظ رحلة هادئة، واطلب المساعدة عند الحاجة، واحتفل بالتقدم خطوة بعد خطوة.`,
    content_en: `## Start with a clear goal\n\nA successful Quran memorization plan is not only about the number of pages. It depends on a clear goal and steady practice. Choose a realistic weekly amount and give revision a fixed place in your schedule.\n\n## Practical steps\n\n1. Divide the passage into short units.\n2. Listen while following the mushaf before reciting from memory.\n3. Repeat gradually and focus on the places that need correction.\n4. Review older memorization every week.\n5. Record progress honestly without harsh comparison.\n\n## The role of family and teacher\n\nFamilies can provide a calm study time and encouragement. A teacher can correct recitation, identify weak points, and adjust the amount to the learner’s level and available time.\n\n## Conclusion\n\nA sustainable plan is better than an ambitious plan that quickly stops. Consistent small steps, supported by good revision, build lasting progress.`,
    content_fr: `## Commencer par un objectif clair\n\nUn plan réussi ne dépend pas seulement du nombre de pages. Il repose sur un objectif réaliste et une pratique régulière, avec une place fixe pour la révision.\n\n## Étapes pratiques\n\n1. Diviser le passage en petites unités.\n2. Écouter en suivant le mushaf avant la récitation de mémoire.\n3. Répéter progressivement et reprendre les passages difficiles.\n4. Réviser l’ancien mémorisé chaque semaine.\n5. Noter les progrès sans comparaison excessive.\n\n## Conclusion\n\nUne progression régulière et raisonnable vaut mieux qu’un programme trop ambitieux.`,
    cover_image: "/images/quran-memorization-techniques.webp", category_ar: "تحفيظ القرآن", category_en: "Quran Memorization", category_fr: "Mémorisation du Coran", author_ar: "فريق الأكاديمية", author_en: "Academy Team", author_fr: "Équipe de l’académie", read_time: 7, sort_order: 10, is_published: true,
  },
  {
    slug: "arabic-foundation-reading-writing",
    title_ar: "كيف نبني أساسًا قويًا في القراءة والكتابة العربية؟",
    title_en: "How to Build a Strong Foundation in Arabic Reading and Writing",
    title_fr: "Comment construire une bonne base en lecture et en écriture arabes",
    excerpt_ar: "مبادئ عملية لتدرّج الطفل أو المبتدئ من معرفة الحروف إلى قراءة كلمات وجمل عربية بثقة.",
    excerpt_en: "Practical principles for moving from recognizing Arabic letters to reading words and sentences with confidence.",
    excerpt_fr: "Des principes pratiques pour passer de la reconnaissance des lettres à la lecture de mots et de phrases.",
    content_ar: `## التأسيس يبدأ من الصوت والشكل\n\nيحتاج المتعلم إلى الربط بين شكل الحرف وصوته ومكانه في الكلمة. لذلك لا يكفي حفظ أسماء الحروف منفردة؛ بل ينبغي التدريب على الحرف في أوله ووسطه وآخره، مع نطقه بوضوح.\n\n## تدرّج مقترح\n\n- التعرف إلى الحروف وأصواتها.\n- التمييز بين الحركات القصيرة.\n- قراءة مقاطع بسيطة ثم كلمات مألوفة.\n- تدريب اليد على كتابة الحروف باتجاهاتها الصحيحة.\n- الانتقال إلى جمل قصيرة ذات معنى.\n\n## كيف نحافظ على الدافعية؟\n\nاجعل التدريب قصيرًا ومتكررًا، واستخدم كلمات قريبة من حياة المتعلم، واحتفل بالتحسن الصغير. التصحيح يكون واضحًا ولطيفًا: نحدد الخطأ، نوضح الطريقة، ثم نعطي فرصة جديدة للمحاولة.\n\n## دور الدرس الفردي\n\nيسمح الدرس الفردي بتحديد الحروف أو الأصوات التي تحتاج إلى مزيد من التدريب، ثم بناء أنشطة مناسبة بدل تكرار منهج واحد للجميع.\n\n## خلاصة\n\nالأساس القوي يتكون من ممارسة متدرجة، وقراءة مسموعة، وكتابة متكررة، ومتابعة تشجع المتعلم على الاستمرار.`,
    content_en: `## Build the connection between shape and sound\n\nLearners need to connect each letter’s shape, sound, and position in a word. Recognizing isolated letter names is only the beginning.\n\n## A practical progression\n\n- Recognize letters and their sounds.\n- Distinguish short vowels.\n- Read simple syllables and familiar words.\n- Practise writing letters in their correct direction.\n- Move to short meaningful sentences.\n\nShort, frequent practice and encouraging correction help learners stay motivated. Individual lessons make it easier to focus on the exact sounds and letters that need support.`,
    content_fr: `## Relier la forme et le son\n\nL’apprenant doit relier la forme de la lettre, son son et sa position dans le mot.\n\n## Progression pratique\n\n- Reconnaître les lettres et leurs sons.\n- Distinguer les voyelles brèves.\n- Lire des syllabes et des mots simples.\n- S’exercer à écrire les lettres correctement.\n- Passer à de courtes phrases.\n\nDes séances courtes et régulières, avec une correction encourageante, favorisent une progression durable.`,
    cover_image: "/images/arabic-foundation-importance.webp", category_ar: "تأسيس العربية", category_en: "Arabic Foundation", category_fr: "Fondation en arabe", author_ar: "فريق الأكاديمية", author_en: "Academy Team", author_fr: "Équipe de l’académie", read_time: 6, sort_order: 11, is_published: true,
  },
]

const classroomVideos = [
  { title_ar: "مقطع تعريفي من حصص الأكاديمية", title_en: "A Short Introduction to Our Academy Lessons", title_fr: "Présentation de nos cours", description_ar: "شاهد جانبًا من أسلوب التعليم والمتابعة في الأكاديمية.", description_en: "See a short example of our teaching and follow-up approach.", description_fr: "Découvrez un exemple de notre méthode d’enseignement et de suivi.", youtube_url: "https://youtube.com/shorts/mAy-mW6gl4s?si=fuCyXAPnTNvF6rD2", youtube_embed_id: "mAy-mW6gl4s", category: "ترويجي", is_featured: true, display_order: 1 },
  { title_ar: "لقطة من التعلم الفردي", title_en: "A Look at One-to-One Learning", title_fr: "Aperçu de l’apprentissage individuel", description_ar: "مقطع قصير يوضح أجواء التعلم الفردي أونلاين.", description_en: "A short clip showing one-to-one online learning.", description_fr: "Un court extrait de l’apprentissage individuel en ligne.", youtube_url: "https://youtu.be/Zy4llxIJNIM?si=MGGVWCU4ZCIA1Uvv", youtube_embed_id: "Zy4llxIJNIM", category: "عام", is_featured: false, display_order: 2 },
  { title_ar: "من داخل الحصة التعليمية", title_en: "Inside an Academy Lesson", title_fr: "Au cœur d’un cours de l’académie", description_ar: "تعرّف إلى جانب من الحصة التعليمية وطريقة التفاعل مع الطالب.", description_en: "See part of a lesson and how the teacher interacts with the learner.", description_fr: "Découvrez un moment de cours et l’interaction avec l’apprenant.", youtube_url: "https://youtu.be/7zntbBQy2q8?si=PE9AMgDzORPIMKu2", youtube_embed_id: "7zntbBQy2q8", category: "عام", is_featured: false, display_order: 3 },
  { title_ar: "تعلم القرآن واللغة العربية أونلاين", title_en: "Learning Quran and Arabic Online", title_fr: "Apprendre le Coran et l’arabe en ligne", description_ar: "مقطع تعريفي عن مسارات التعلم الأونلاين في الأكاديمية.", description_en: "An introduction to the academy’s online learning paths.", description_fr: "Présentation des parcours en ligne de l’académie.", youtube_url: "https://youtu.be/dGmdFsHm9Q8?si=39x1oQgqFDjjfsCn", youtube_embed_id: "dGmdFsHm9Q8", category: "قرآن كريم", is_featured: false, display_order: 4 },
  { title_ar: "شاهد أسلوب المتابعة والتعليم", title_en: "See Our Teaching and Follow-up Approach", title_fr: "Découvrez notre méthode de suivi", description_ar: "مقطع إضافي من المحتوى المرئي المنشور في الأكاديمية.", description_en: "An additional clip from the academy’s published visual content.", description_fr: "Un extrait supplémentaire du contenu vidéo de l’académie.", youtube_url: "https://youtu.be/YzChqKd6TT8?si=A-vzLVx7gcyv1N1I", youtube_embed_id: "YzChqKd6TT8", category: "عام", is_featured: false, display_order: 5 },
].map((video) => ({ ...video, teacher_name_ar: "فريق الأكاديمية", teacher_name_en: "Academy Team", teacher_name_fr: "Équipe de l’académie", thumbnail_url: `https://img.youtube.com/vi/${video.youtube_embed_id}/hqdefault.jpg`, duration_seconds: null, is_published: true, show_on_landing_pages: true }))

const faqs = [
  { id: 1001, question_ar: "هل يمكن بدء الدراسة من مستوى المبتدئ؟", question_en: "Can a beginner start?", question_fr: "Un débutant peut-il commencer ?", answer_ar: "نعم، يبدأ المسار من مستوى الطالب الحالي، سواء في حفظ القرآن أو القراءة والكتابة بالعربية.", answer_en: "Yes. The learning path starts from the learner’s current level, whether in Quran memorization or Arabic reading and writing.", answer_fr: "Oui. Le parcours commence au niveau actuel de l’apprenant, en mémorisation du Coran ou en lecture et écriture arabes.", category: "general", sort_order: 0, is_active: true },
  { id: 1002, question_ar: "كيف تتم الحصص أونلاين؟", question_en: "How are online lessons delivered?", question_fr: "Comment se déroulent les cours en ligne ?", answer_ar: "تتم الحصص الفردية مباشرة عبر وسيلة الاجتماع المعتمدة، ويُنسق الموعد والمستوى والبرنامج قبل البدء.", answer_en: "Lessons are delivered live one-to-one through the approved meeting platform, with the time, level, and program agreed before starting.", answer_fr: "Les cours sont individuels et en direct sur la plateforme retenue, après accord sur l’horaire, le niveau et le programme.", category: "general", sort_order: 1, is_active: true },
  { id: 1003, question_ar: "هل توجد حصة تجريبية؟", question_en: "Is a trial lesson available?", question_fr: "Une séance d’essai est-elle disponible ?", answer_ar: "يمكن طلب الحصة التجريبية الأولى عبر التواصل مع الأكاديمية، ثم يحدد المعلم المسار الأنسب بعد التعرف إلى احتياج الطالب.", answer_en: "A first trial lesson can be requested through the academy, after which the teacher can recommend a suitable path.", answer_fr: "Une première séance d’essai peut être demandée auprès de l’académie afin de proposer un parcours adapté.", category: "general", sort_order: 2, is_active: true },
]

const legalPages = [
  ["terms", "ar", "شروط الاستخدام", "تقدم الأكاديمية خدمات تعليمية أونلاين في تحفيظ القرآن وتأسيس اللغة العربية. يلتزم المستخدم بتقديم معلومات صحيحة واحترام المعلمين والمنصة. يتم الاتفاق على المواعيد والباقات ووسيلة التواصل قبل بدء الخدمة. لا يجوز استخدام محتوى المنصة أو حسابات الإدارة بطريقة تضر بالأكاديمية أو بالطلاب. قد تتغير هذه الشروط عند تحديث الخدمات، ويظهر الإصدار المعتمد في هذه الصفحة."],
  ["terms", "en", "Terms of Use", "The academy provides online educational services in Quran learning and Arabic foundation. Users must provide accurate information and respect teachers and the platform. Lesson schedules, packages, and communication methods are agreed before service begins. Platform content and administration accounts may not be misused."],
  ["terms", "fr", "Conditions d’utilisation", "L’académie propose des services éducatifs en ligne pour l’apprentissage du Coran et les bases de l’arabe. L’utilisateur doit fournir des informations exactes et respecter les enseignants et la plateforme. Les horaires, forfaits et moyens de communication sont convenus avant le début du service."],
  ["privacy", "ar", "سياسة الخصوصية", "نستخدم البيانات التي يرسلها المستخدم للتواصل وتنظيم الخدمات التعليمية وتحسين تجربة الموقع. نحد من الوصول إلى البيانات على قدر الحاجة التشغيلية، ولا نبيع بيانات المستخدمين. قد تعتمد بعض الخدمات على مزودين موثوقين مثل الاستضافة وقواعد البيانات، وتتم معالجة البيانات وفق إعدادات تلك الخدمات. لطلب تصحيح أو حذف بياناتك، تواصل مع الأكاديمية عبر القنوات الرسمية."],
  ["privacy", "en", "Privacy Policy", "We use information submitted by users to communicate, organize educational services, and improve the website. Access is limited to operational needs, and user data is not sold. Some services rely on trusted providers such as hosting and database services. Contact the academy through official channels to request correction or deletion of your data."],
  ["privacy", "fr", "Politique de confidentialité", "Nous utilisons les informations fournies pour communiquer, organiser les services éducatifs et améliorer le site. L’accès est limité aux besoins opérationnels et les données ne sont pas vendues. Certains services utilisent des prestataires de confiance pour l’hébergement et la base de données. Contactez l’académie pour demander la correction ou la suppression de vos données."],
  ["refund-policy", "ar", "سياسة الاسترداد", "تتم مراجعة طلبات الإلغاء أو الاسترداد بحسب حالة الباقة والدروس التي تم تنفيذها والاتفاق المسبق مع الأكاديمية. قبل الدفع أو بدء الباقة، اسأل عن التفاصيل الخاصة بالبرنامج ووسيلة السداد. لا تشمل هذه الصفحة أي عملية دفع أو تفويض مالي تلقائي؛ يتم الاتفاق على الإجراءات عبر القنوات الرسمية."],
  ["refund-policy", "en", "Refund Policy", "Cancellation and refund requests are reviewed according to the package status, lessons delivered, and the prior agreement with the academy. Ask for program and payment details before starting a package. This page does not initiate payments or authorize automatic charges."],
  ["refund-policy", "fr", "Politique de remboursement", "Les demandes d’annulation ou de remboursement sont examinées selon l’état du forfait, les cours réalisés et l’accord préalable avec l’académie. Demandez les détails du programme et du paiement avant de commencer. Cette page n’initie aucun paiement automatique."],
].map(([page_slug, locale, title, content]) => ({ page_slug, locale, title, content }))

const widgets = [
  { widget_type: "whatsapp_button", config_json: { position: "right", phone: "+201130127894", size: "medium", color: "#25D366", showLabel: true, labelAr: "تواصل معنا", labelEn: "Contact us", labelFr: "Contactez-nous" }, is_enabled: true, display_order: 0 },
  { widget_type: "navbar", config_json: { items: ["home", "about", "quran", "arabic", "teachers", "reviews", "library", "classroom", "games", "faq", "blog", "contact"] }, is_enabled: true, display_order: 1 },
]

const pages = [
  { slug: "about", title_ar: "عن أكاديمية الحافظ المتميز", title_en: "About Al-Hafiz Academy", title_fr: "À propos de l’académie", meta_description_ar: "تعرف إلى أكاديمية الحافظ المتميز وخدماتها التعليمية أونلاين.", meta_description_en: "Learn about Al-Hafiz Academy and its online educational services.", meta_description_fr: "Découvrez l’académie et ses services éducatifs en ligne.", template_type: "content", content_json: { sections: [{ heading: "رسالتنا", body: "نقدم مسارات تعليمية أونلاين لتحفيظ القرآن وتأسيس اللغة العربية، مع مراعاة مستوى الطالب وهدفه ووقته." }, { heading: "كيف نبدأ", body: "يبدأ التواصل بتحديد البرنامج والمستوى والوقت المناسب، ثم تُرتب الحصة التجريبية أو الخطة التعليمية." }] }, settings_json: { source: "preview-approved-content" }, is_published: true, is_home_page: false },
  { slug: "faq", title_ar: "الأسئلة الشائعة", title_en: "Frequently Asked Questions", title_fr: "Questions fréquentes", meta_description_ar: "إجابات مختصرة عن الدراسة أونلاين والبداية مع الأكاديمية.", meta_description_en: "Answers about online learning and starting with the academy.", meta_description_fr: "Réponses sur l’apprentissage en ligne et le début du parcours.", template_type: "faq", content_json: { source: "faq_items" }, settings_json: { source: "preview-approved-content" }, is_published: true, is_home_page: false },
]

async function main() {
  const apply = process.argv.includes("--apply")
  console.log(JSON.stringify({ mode: apply ? "apply" : "dry-run", blogPosts: blogPosts.length, faqs: faqs.length, legalPages: legalPages.length, widgets: widgets.length, pages: pages.length, classroomVideos: classroomVideos.length }, null, 2))
  if (!apply) return
  if (process.env.VERCEL_ENV !== "preview" || process.env.MIGRATION_TARGET !== "preview") throw new Error("مرفوض: هذا السكربت يعمل على Preview فقط")
  if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) throw new Error("متغيرات Supabase Preview غير موجودة")
  const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY)
  const fail = (label: string, error: any) => { if (error) throw new Error(`${label}: ${error.message}`) }
  const blog = await db.from("blog_posts").upsert(blogPosts, { onConflict: "slug" }); fail("المدونة", blog.error)
  const faq = await db.from("faq_items").upsert(faqs, { onConflict: "id" }); fail("الأسئلة العامة", faq.error)
  const legal = await db.from("legal_pages").upsert(legalPages, { onConflict: "page_slug,locale" }); fail("الصفحات القانونية", legal.error)
  for (const widget of widgets) { const result = await db.from("widget_configs").upsert(widget, { onConflict: "widget_type" }); fail(`الودجت ${widget.widget_type}`, result.error) }
  for (const page of pages) { const result = await db.from("site_pages").upsert(page, { onConflict: "slug" }); fail(`صفحة ${page.slug}`, result.error) }
  for (const video of classroomVideos) { const existing = await db.from("classroom_videos").select("id").eq("youtube_embed_id", video.youtube_embed_id).limit(1).maybeSingle(); fail(`فحص الفيديو ${video.youtube_embed_id}`, existing.error); if (!existing.data) { const result = await db.from("classroom_videos").insert(video); fail(`الفيديو ${video.youtube_embed_id}`, result.error) } }
  console.log("تمت إضافة محتوى Preview للمدونة والأسئلة القانونية والودجات وصفحات محرر الصفحات.")
  console.log("تمت إضافة روابط YouTube إلى مركز الفيديوهات؛ صفحات الدول تستدعي نفس السجلات وتعيد تنسيقها حسب الثيم.")
}
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1 })
