-- 026: Multi-source analytics MVP storage.
-- Stores aggregate report snapshots and confirmed conversion events only.

CREATE TABLE IF NOT EXISTS public.analytics_sources (
  source_key TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  consent_required BOOLEAN NOT NULL DEFAULT FALSE,
  last_attempt_at TIMESTAMPTZ,
  last_success_at TIMESTAMPTZ,
  last_status TEXT NOT NULL DEFAULT 'not_configured' CHECK (last_status IN ('healthy','delayed','failed','disabled','consent_required','not_configured')),
  last_error_code TEXT,
  last_error_message TEXT,
  failure_count INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.analytics_sync_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_key TEXT NOT NULL REFERENCES public.analytics_sources(source_key) ON DELETE CASCADE,
  report_type TEXT NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  source_updated_at TIMESTAMPTZ,
  metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  dimensions JSONB NOT NULL DEFAULT '{}'::jsonb,
  schema_version INTEGER NOT NULL DEFAULT 1,
  response_hash TEXT,
  UNIQUE (source_key, report_type, period_start, period_end, schema_version)
);

CREATE INDEX IF NOT EXISTS analytics_snapshots_lookup_idx
  ON public.analytics_sync_snapshots (source_key, report_type, period_start, period_end, fetched_at DESC);

CREATE TABLE IF NOT EXISTS public.internal_analytics_events (
  event_id TEXT PRIMARY KEY,
  event_name TEXT NOT NULL CHECK (event_name IN ('contact_form_submit','whatsapp_click','telegram_click','email_click','trial_booking_click')),
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  page_path TEXT,
  program TEXT,
  country_group TEXT,
  source_group TEXT,
  device_type TEXT,
  consent_state TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS internal_analytics_events_lookup_idx
  ON public.internal_analytics_events (event_name, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.analytics_event_deliveries (
  event_id TEXT NOT NULL REFERENCES public.internal_analytics_events(event_id) ON DELETE CASCADE,
  source_key TEXT NOT NULL REFERENCES public.analytics_sources(source_key) ON DELETE CASCADE,
  delivery_status TEXT NOT NULL DEFAULT 'pending' CHECK (delivery_status IN ('pending','sent','failed','not_applicable')),
  attempt_count INTEGER NOT NULL DEFAULT 0,
  last_attempt_at TIMESTAMPTZ,
  last_error_message TEXT,
  PRIMARY KEY (event_id, source_key)
);

INSERT INTO public.analytics_sources (source_key, display_name, enabled, consent_required, last_status)
VALUES
  ('ga4', 'Google Analytics 4', TRUE, TRUE, 'not_configured'),
  ('search_console', 'Google Search Console', TRUE, FALSE, 'not_configured'),
  ('internal', 'أحداث الموقع المؤكدة', TRUE, FALSE, 'healthy'),
  ('clarity', 'Microsoft Clarity', TRUE, TRUE, 'consent_required'),
  ('vercel', 'Vercel Web Analytics', TRUE, TRUE, 'not_configured'),
  ('speed_insights', 'Vercel Speed Insights', TRUE, FALSE, 'not_configured')
ON CONFLICT (source_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  enabled = EXCLUDED.enabled,
  consent_required = EXCLUDED.consent_required,
  updated_at = NOW();

ALTER TABLE public.analytics_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_sync_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_event_deliveries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS analytics_sources_service_only ON public.analytics_sources;
CREATE POLICY analytics_sources_service_only ON public.analytics_sources
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS analytics_snapshots_service_only ON public.analytics_sync_snapshots;
CREATE POLICY analytics_snapshots_service_only ON public.analytics_sync_snapshots
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS internal_events_service_only ON public.internal_analytics_events;
CREATE POLICY internal_events_service_only ON public.internal_analytics_events
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS event_deliveries_service_only ON public.analytics_event_deliveries;
CREATE POLICY event_deliveries_service_only ON public.analytics_event_deliveries
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);

COMMENT ON TABLE public.analytics_sync_snapshots IS 'Aggregate snapshots from GA4 and Search Console; never stores raw visitor identifiers.';
COMMENT ON TABLE public.internal_analytics_events IS 'Confirmed business events only; do not store form contents or contact details.';

GRANT ALL ON public.analytics_sources TO service_role;
GRANT ALL ON public.analytics_sync_snapshots TO service_role;
GRANT ALL ON public.internal_analytics_events TO service_role;
GRANT ALL ON public.analytics_event_deliveries TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
