-- CLEAN, PROVIDER-NEUTRAL POSTGRES BASELINE FOR AN ISOLATED PREVIEW.
-- This file creates structure only. It does not read or copy data from any old database.
-- It is intentionally outside supabase/migrations/ and MUST NOT be auto-applied yet.
-- Apply only to a confirmed, empty, isolated preview database after provider approval.

BEGIN;

CREATE TABLE site_content (
  key TEXT PRIMARY KEY,
  content_ar TEXT,
  content_en TEXT,
  content_fr TEXT,
  section TEXT NOT NULL DEFAULT 'general',
  type TEXT NOT NULL DEFAULT 'text',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX site_content_active_section ON site_content(is_active, section);

CREATE TABLE site_settings (
  setting_key TEXT PRIMARY KEY,
  setting_value TEXT NOT NULL,
  value_type TEXT NOT NULL DEFAULT 'text',
  label TEXT,
  description TEXT,
  category TEXT NOT NULL DEFAULT 'general',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX site_settings_category ON site_settings(category, setting_key);

CREATE TABLE site_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  area_type TEXT NOT NULL CHECK (area_type IN ('global', 'country')),
  country_code CHAR(2),
  name_ar TEXT NOT NULL,
  name_en TEXT,
  name_fr TEXT,
  currency_code CHAR(3) NOT NULL,
  currency_symbol TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ((area_type = 'global' AND country_code IS NULL) OR (area_type = 'country' AND country_code IS NOT NULL))
);
CREATE UNIQUE INDEX site_areas_country_code_unique ON site_areas(country_code) WHERE country_code IS NOT NULL;

CREATE TABLE area_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id BIGINT NOT NULL REFERENCES site_areas(id) ON DELETE CASCADE,
  content_key TEXT NOT NULL,
  content_ar TEXT,
  content_en TEXT,
  content_fr TEXT,
  content_type TEXT NOT NULL DEFAULT 'text',
  section TEXT NOT NULL DEFAULT 'general',
  href TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (area_id, content_key)
);
CREATE INDEX area_content_public_order ON area_content(area_id, is_active, section, sort_order);

CREATE TABLE area_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id BIGINT NOT NULL REFERENCES site_areas(id) ON DELETE CASCADE,
  program TEXT NOT NULL CHECK (program IN ('quran', 'arabic', 'other')),
  package_key TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  name_en TEXT,
  name_fr TEXT,
  description_ar TEXT,
  description_en TEXT,
  description_fr TEXT,
  price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  currency_code CHAR(3) NOT NULL,
  billing_period TEXT NOT NULL DEFAULT 'month',
  sessions_per_month INTEGER NOT NULL CHECK (sessions_per_month > 0),
  duration_minutes SMALLINT NOT NULL DEFAULT 30 CHECK (duration_minutes BETWEEN 1 AND 240),
  features_ar JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(features_ar) = 'array'),
  features_en JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(features_en) = 'array'),
  features_fr JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(features_fr) = 'array'),
  is_popular BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (area_id, package_key)
);
CREATE INDEX area_packages_public_order ON area_packages(area_id, program, is_active, sort_order);

-- Enforce that package prices cannot be stored under a different country's currency.
CREATE FUNCTION enforce_area_package_currency() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE expected_currency TEXT;
BEGIN
  SELECT currency_code INTO expected_currency FROM site_areas WHERE id = NEW.area_id;
  IF expected_currency IS NULL OR upper(NEW.currency_code) <> upper(expected_currency) THEN
    RAISE EXCEPTION 'Package currency must match its site area currency';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER area_package_currency_guard
  BEFORE INSERT OR UPDATE OF area_id, currency_code ON area_packages
  FOR EACH ROW EXECUTE FUNCTION enforce_area_package_currency();

CREATE TABLE area_faq_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id BIGINT NOT NULL REFERENCES site_areas(id) ON DELETE CASCADE,
  question_key TEXT NOT NULL,
  question_ar TEXT NOT NULL,
  question_en TEXT,
  question_fr TEXT,
  answer_ar TEXT NOT NULL,
  answer_en TEXT,
  answer_fr TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (area_id, question_key)
);
CREATE INDEX area_faq_public_order ON area_faq_items(area_id, is_active, sort_order);

CREATE TABLE area_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id BIGINT NOT NULL REFERENCES site_areas(id) ON DELETE CASCADE,
  link_key TEXT NOT NULL,
  label_ar TEXT NOT NULL,
  label_en TEXT,
  label_fr TEXT,
  href TEXT NOT NULL,
  link_type TEXT NOT NULL DEFAULT 'internal',
  is_external BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (area_id, link_key),
  CHECK (href LIKE '/%' OR href ~ '^https://')
);
CREATE INDEX area_links_public_order ON area_links(area_id, is_active, sort_order);

CREATE TABLE area_themes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id BIGINT NOT NULL UNIQUE REFERENCES site_areas(id) ON DELETE CASCADE,
  theme_name_ar TEXT NOT NULL,
  theme_name_en TEXT,
  primary_color TEXT NOT NULL CHECK (primary_color ~ '^#[0-9A-Fa-f]{6}$'),
  secondary_color TEXT NOT NULL CHECK (secondary_color ~ '^#[0-9A-Fa-f]{6}$'),
  accent_color TEXT NOT NULL CHECK (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  background_color TEXT NOT NULL CHECK (background_color ~ '^#[0-9A-Fa-f]{6}$'),
  text_color TEXT NOT NULL CHECK (text_color ~ '^#[0-9A-Fa-f]{6}$'),
  quran_fact_title_ar TEXT,
  quran_fact_body_ar TEXT,
  quran_fact_reference_ar TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE area_cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id BIGINT NOT NULL REFERENCES site_areas(id) ON DELETE CASCADE,
  city_key TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  region_name TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (area_id, city_key)
);
CREATE INDEX area_cities_public_order ON area_cities(area_id, is_active, sort_order);

CREATE TABLE area_timezones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id BIGINT NOT NULL REFERENCES site_areas(id) ON DELETE CASCADE,
  timezone_name TEXT NOT NULL,
  label_ar TEXT NOT NULL,
  label_en TEXT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (area_id, timezone_name)
);
CREATE INDEX area_timezones_public_order ON area_timezones(area_id, is_active, sort_order);
CREATE UNIQUE INDEX one_primary_timezone_per_area
  ON area_timezones(area_id) WHERE is_primary = TRUE AND is_active = TRUE;

CREATE TABLE admin_change_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id BIGINT REFERENCES site_areas(id) ON DELETE SET NULL,
  actor_email TEXT NOT NULL,
  resource TEXT NOT NULL,
  record_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete', 'reorder')),
  before_data JSONB,
  after_data JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX admin_change_log_area_created ON admin_change_log(area_id, created_at DESC);

COMMIT;
