-- CLEAN, PROVIDER-NEUTRAL POSTGRES SCHEMA FOR ADMIN CONTENT.
-- No INSERT/SELECT from an old database and no production-like seed records.
-- Execute only after 0001_clean_baseline.sql on a new isolated database.
BEGIN;

-- Generic JSONB store currently used by legacy dashboard collections
-- (teachers, reviews, messages, and site settings). Keep server-only access.
CREATE TABLE admin_content (
  content_type TEXT NOT NULL,
  content_id TEXT NOT NULL,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (content_type, content_id)
);
CREATE INDEX admin_content_type_id ON admin_content(content_type, content_id);

CREATE OR REPLACE FUNCTION replace_admin_content_atomic(p_content_type TEXT, payload JSONB)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  IF p_content_type NOT IN ('teachers', 'reviews', 'messages', 'settings') THEN
    RAISE EXCEPTION 'Unsupported admin content type';
  END IF;
  IF payload IS NULL OR jsonb_typeof(payload) <> 'array' THEN
    RAISE EXCEPTION 'Admin content payload must be a JSON array';
  END IF;

  DELETE FROM admin_content WHERE content_type = p_content_type;
  INSERT INTO admin_content (content_type, content_id, data, updated_at)
  SELECT p_content_type, item.content_id, item.data, NOW()
  FROM jsonb_to_recordset(payload) AS item(content_id TEXT, data JSONB);
END;
$$;

-- Global packages are distinct from country-specific area_packages.
CREATE TABLE packages (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('quran', 'arabic')),
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL DEFAULT '',
  name_fr TEXT NOT NULL DEFAULT '',
  sessions INTEGER NOT NULL CHECK (sessions > 0),
  price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  duration INTEGER NOT NULL DEFAULT 30 CHECK (duration BETWEEN 1 AND 240),
  features_ar TEXT NOT NULL DEFAULT '',
  features_en TEXT NOT NULL DEFAULT '',
  features_fr TEXT NOT NULL DEFAULT '',
  popular BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX packages_active_order ON packages(active, type, sort_order);

-- Public FAQ is a separate domain from each country's area_faq_items.
CREATE TABLE faq_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_ar TEXT NOT NULL,
  question_en TEXT,
  question_fr TEXT,
  answer_ar TEXT NOT NULL,
  answer_en TEXT,
  answer_fr TEXT,
  category VARCHAR(50) NOT NULL DEFAULT 'general',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX faq_items_active_order ON faq_items(is_active, category, sort_order);

-- Replace the editable global package list in one database transaction.
CREATE OR REPLACE FUNCTION replace_packages_atomic(payload JSONB)
RETURNS SETOF packages
LANGUAGE plpgsql
AS $$
BEGIN
  IF payload IS NULL OR jsonb_typeof(payload) <> 'array' THEN
    RAISE EXCEPTION 'Package payload must be a JSON array';
  END IF;

  DELETE FROM packages;
  INSERT INTO packages (
    id, type, name_ar, name_en, name_fr, sessions, price, duration,
    features_ar, features_en, features_fr, popular, active, sort_order, updated_at
  )
  SELECT
    item.id, item.type, item.name_ar, item.name_en, item.name_fr,
    item.sessions, item.price, item.duration, item.features_ar,
    item.features_en, item.features_fr, item.popular, item.active,
    item.sort_order, NOW()
  FROM jsonb_to_recordset(payload) AS item(
    id TEXT, type TEXT, name_ar TEXT, name_en TEXT, name_fr TEXT,
    sessions INTEGER, price NUMERIC(12,2), duration INTEGER,
    features_ar TEXT, features_en TEXT, features_fr TEXT,
    popular BOOLEAN, active BOOLEAN, sort_order INTEGER
  );

  RETURN QUERY SELECT * FROM packages ORDER BY type, sort_order;
END;
$$;

COMMIT;
