-- CLEAN, PROVIDER-NEUTRAL TABLES FOR THE REMAINING EDITABLE ADMIN DOMAINS.
-- Apply only after 0001_clean_baseline.sql and 0002_admin_content.sql.
-- This file defines empty structures only; it imports no old data and contains
-- no payment/order tables. All writes must go through authenticated server APIs.
BEGIN;

CREATE TABLE IF NOT EXISTS site_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title_ar TEXT NOT NULL DEFAULT '',
  title_en TEXT NOT NULL DEFAULT '',
  title_fr TEXT NOT NULL DEFAULT '',
  meta_description_ar TEXT NOT NULL DEFAULT '',
  meta_description_en TEXT NOT NULL DEFAULT '',
  meta_description_fr TEXT NOT NULL DEFAULT '',
  template_type TEXT NOT NULL DEFAULT 'custom',
  content_json JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(content_json) = 'object'),
  settings_json JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(settings_json) = 'object'),
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  is_home_page BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS site_pages_single_home_page ON site_pages(is_home_page) WHERE is_home_page;
CREATE INDEX IF NOT EXISTS site_pages_published_updated ON site_pages(is_published, updated_at DESC);

CREATE TABLE IF NOT EXISTS widget_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  widget_type TEXT NOT NULL UNIQUE CHECK (widget_type IN ('whatsapp_button', 'navbar')),
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config_json) = 'object'),
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER NOT NULL DEFAULT 0 CHECK (display_order >= 0),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS theme_customizations (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  primary_color TEXT NOT NULL DEFAULT '#1a4d2e' CHECK (primary_color ~ '^#[0-9A-Fa-f]{6}$'),
  accent_color TEXT NOT NULL DEFAULT '#d4af37' CHECK (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  background_color TEXT NOT NULL DEFAULT '#ffffff' CHECK (background_color ~ '^#[0-9A-Fa-f]{6}$'),
  foreground_color TEXT NOT NULL DEFAULT '#171717' CHECK (foreground_color ~ '^#[0-9A-Fa-f]{6}$'),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Saudi/UAE specialized landing-page copy is stored as versioned JSON config,
-- while country prices remain owned by area_packages and keep their currency.
CREATE TABLE IF NOT EXISTS landing_page_configs (
  slug TEXT PRIMARY KEY CHECK (slug IN ('saudi-arabia', 'uae')),
  config_json JSONB NOT NULL CHECK (jsonb_typeof(config_json) = 'object'),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS digital_library_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title_ar TEXT NOT NULL CHECK (length(trim(title_ar)) > 0),
  title_en TEXT,
  title_fr TEXT,
  description_ar TEXT,
  description_en TEXT,
  description_fr TEXT,
  surahs_ar TEXT,
  author_ar TEXT,
  author_en TEXT,
  author_fr TEXT,
  category TEXT NOT NULL DEFAULT 'general',
  tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  drive_url TEXT NOT NULL CHECK (drive_url ~ '^https://'),
  file_type TEXT NOT NULL DEFAULT 'pdf' CHECK (file_type IN ('pdf', 'document', 'text', 'image', 'audio')),
  cover_url TEXT,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS digital_library_published_order ON digital_library_documents(is_published, sort_order, created_at DESC);

CREATE TABLE IF NOT EXISTS classroom_videos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title_ar TEXT NOT NULL CHECK (length(trim(title_ar)) > 0),
  title_en TEXT NOT NULL DEFAULT '',
  title_fr TEXT NOT NULL DEFAULT '',
  description_ar TEXT NOT NULL DEFAULT '',
  description_en TEXT NOT NULL DEFAULT '',
  description_fr TEXT NOT NULL DEFAULT '',
  teacher_name_ar TEXT NOT NULL DEFAULT '',
  teacher_name_en TEXT NOT NULL DEFAULT '',
  teacher_name_fr TEXT NOT NULL DEFAULT '',
  youtube_url TEXT NOT NULL CHECK (youtube_url ~ '^https://'),
  youtube_embed_id TEXT NOT NULL UNIQUE CHECK (length(youtube_embed_id) = 11),
  thumbnail_url TEXT,
  category TEXT NOT NULL DEFAULT 'عام',
  duration_seconds INTEGER CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  show_on_landing_pages BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER NOT NULL DEFAULT 0 CHECK (display_order >= 0),
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS classroom_videos_public_order ON classroom_videos(is_published, display_order, created_at DESC);

CREATE TABLE IF NOT EXISTS blog_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title_ar TEXT NOT NULL CHECK (length(trim(title_ar)) > 0),
  title_en TEXT NOT NULL DEFAULT '',
  title_fr TEXT NOT NULL DEFAULT '',
  excerpt_ar TEXT NOT NULL DEFAULT '',
  excerpt_en TEXT NOT NULL DEFAULT '',
  excerpt_fr TEXT NOT NULL DEFAULT '',
  content_ar TEXT NOT NULL DEFAULT '',
  content_en TEXT NOT NULL DEFAULT '',
  content_fr TEXT NOT NULL DEFAULT '',
  cover_image TEXT NOT NULL DEFAULT '/images/hero-children.webp',
  category_ar TEXT NOT NULL DEFAULT 'عام',
  category_en TEXT NOT NULL DEFAULT 'General',
  category_fr TEXT NOT NULL DEFAULT 'Général',
  author_ar TEXT NOT NULL DEFAULT 'فريق الأكاديمية',
  author_en TEXT NOT NULL DEFAULT 'Academy Team',
  author_fr TEXT NOT NULL DEFAULT 'Équipe de l’académie',
  read_time INTEGER NOT NULL DEFAULT 5 CHECK (read_time BETWEEN 1 AND 180),
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS blog_posts_public_order ON blog_posts(is_published, sort_order, published_at DESC);

CREATE TABLE IF NOT EXISTS legal_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  page_slug TEXT NOT NULL CHECK (page_slug IN ('terms', 'privacy', 'refund-policy')),
  locale TEXT NOT NULL CHECK (locale IN ('ar', 'en', 'fr')),
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  content TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (page_slug, locale)
);

-- These are CMS profile records, not authentication credentials. Authentication
-- remains the verified server-side admin session until a separate identity
-- provider and session-to-user mapping are explicitly implemented.
CREATE TABLE IF NOT EXISTS cms_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id UUID UNIQUE,
  email TEXT NOT NULL UNIQUE CHECK (email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
  full_name TEXT,
  role_type TEXT NOT NULL CHECK (role_type IN ('admin', 'supervisor', 'teacher', 'student')),
  avatar_url TEXT,
  phone TEXT,
  bio TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS cms_users_role_active ON cms_users(role_type, is_active);

CREATE TABLE IF NOT EXISTS cms_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_type TEXT NOT NULL CHECK (role_type IN ('admin', 'supervisor', 'teacher', 'student')),
  module_name TEXT NOT NULL CHECK (length(trim(module_name)) > 0),
  action TEXT NOT NULL CHECK (action IN ('create', 'read', 'update', 'delete', 'publish')),
  is_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (role_type, module_name, action)
);

-- The game catalog is metadata-only. component_key must be checked against the
-- app's allowlisted game registry; never evaluate database-supplied code.
CREATE TABLE IF NOT EXISTS educational_games (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  component_key TEXT NOT NULL,
  title_ar TEXT NOT NULL,
  title_en TEXT NOT NULL DEFAULT '',
  title_fr TEXT NOT NULL DEFAULT '',
  description_ar TEXT NOT NULL DEFAULT '',
  description_en TEXT NOT NULL DEFAULT '',
  description_fr TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT 'general',
  difficulty TEXT NOT NULL DEFAULT 'beginner' CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
  icon_key TEXT NOT NULL DEFAULT 'gamepad',
  accent_color TEXT NOT NULL DEFAULT '#1a4d2e' CHECK (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS educational_games_public_order ON educational_games(is_published, sort_order);

-- Restrict browser-role access. Supabase service_role bypasses RLS; on other
-- providers the application DB role must be a trusted owner/service role.
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'site_pages', 'widget_configs', 'theme_customizations', 'landing_page_configs',
    'digital_library_documents', 'classroom_videos', 'blog_posts', 'legal_pages',
    'cms_users', 'cms_permissions', 'educational_games'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END;
$$;

COMMIT;
