import type { Metadata } from "next"
import Link from "next/link"
import { Clock3, MapPin, MessageCircle, Timer } from "lucide-react"
import { getAreaLandingData, getAreaLinkHref, getAreaWhatsAppUrl, toAreaDisplayPlan } from "@/lib/country-content"
import { getPublishedClassroomVideos } from "@/lib/classroom-videos"
import { countryPages } from "@/components/layout/country-pages-section"
import { switzerlandLandingConfig, getSwitzerlandWhatsAppUrl } from "@/lib/switzerland-landing-config"
import { SwitzerlandTimeDial } from "./switzerland-time-dial"
import { SwitzerlandVideoStack } from "./switzerland-video-stack"

const canonical = switzerlandLandingConfig.seo.canonical

export const metadata: Metadata = {
  title: switzerlandLandingConfig.seo.title,
  description: switzerlandLandingConfig.seo.description,
  keywords: ["تحفيظ القرآن أونلاين في سويسرا", "تحفيظ القرآن في زيورخ", "تحفيظ القرآن في جنيف", "تعليم العربية أونلاين في سويسرا", "دروس قرآن في بازل", "تعلم العربية في برن", "باقات تحفيظ القرآن بالفرنك السويسري"],
  alternates: { canonical, languages: { ar: canonical, "x-default": canonical } },
  openGraph: { title: switzerlandLandingConfig.seo.title, description: switzerlandLandingConfig.seo.description, url: canonical, locale: "ar_CH", type: "website", images: [{ url: "https://quran-elhafez.com/images/og-default.webp", width: 1200, height: 630, alt: "أكاديمية الحافظ المتميز في سويسرا" }] },
  twitter: { card: "summary_large_image", title: switzerlandLandingConfig.seo.title, description: switzerlandLandingConfig.seo.description, images: ["https://quran-elhafez.com/images/og-default.webp"] },
}

export default async function SwitzerlandPage() {
  const [areaData, videos] = await Promise.all([getAreaLandingData("switzerland"), getPublishedClassroomVideos()])
  const quranPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "quran")
  const arabicPlans = areaData.packages.map(toAreaDisplayPlan).filter((plan) => plan.program === "arabic")
  const quranPrices = quranPlans.length >= 4 ? quranPlans.slice(0, 4).map((plan) => plan.price) : switzerlandLandingConfig.quranPrices
  const arabicPrices = arabicPlans.length >= 4 ? arabicPlans.slice(0, 4).map((plan) => plan.price) : switzerlandLandingConfig.arabicPrices
  const cities = areaData.cities.length ? areaData.cities.map((city) => city.name_ar) : switzerlandLandingConfig.cities
  const faq = areaData.faq.length ? areaData.faq.map((item) => [item.question_ar, item.answer_ar] as const) : switzerlandLandingConfig.faq
  const baseContact = getAreaLinkHref(areaData.links, "whatsapp", getSwitzerlandWhatsAppUrl())
  const trialUrl = getAreaWhatsAppUrl(areaData.links, "حصة تجريبية مجانية في سويسرا", baseContact)
  const packageUrl = getAreaWhatsAppUrl(areaData.links, "باقات القرآن أو العربية في سويسرا", baseContact)
  const jsonLd = { "@context": "https://schema.org", "@graph": [
    { "@type": "WebPage", "@id": `${canonical}#webpage`, url: canonical, name: switzerlandLandingConfig.seo.title, description: switzerlandLandingConfig.seo.description, inLanguage: "ar" },
    { "@type": "EducationalOrganization", "@id": `${canonical}#organization`, name: "أكاديمية الحافظ المتميز", url: "https://quran-elhafez.com/", areaServed: { "@type": "Country", name: "Switzerland" } },
    { "@type": "Course", name: "تحفيظ القرآن أونلاين في سويسرا", description: "حصص فردية للحفظ والمراجعة والقراءة عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: quranPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "CHF", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "Course", name: "تأسيس العربية أونلاين في سويسرا", description: "حصص فردية لبناء أساس القراءة والفهم بالعربية عبر الإنترنت.", provider: { "@id": `${canonical}#organization` }, offers: arabicPrices.map((price, index) => ({ "@type": "Offer", price, priceCurrency: "CHF", category: `${[4, 8, 12, 16][index]} حصص شهريًا`, url: canonical })) },
    { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
  ] }

  return <main dir="rtl" className="min-h-screen overflow-hidden bg-[#FFF8EA] text-[#17211F]"><header className="border-b border-[#E6F0EA] bg-[#FFF8EA] px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><span className="font-black tracking-wide">سويسرا · القرآن والعربية</span><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full bg-[#D52B1E] px-4 py-2 text-sm font-black text-white">احجز الحصة التجريبية</a></div></header>
    <section className="relative overflow-hidden bg-[#164A41] px-5 pb-20 pt-16 text-[#FFF8EA] sm:px-8 lg:pb-28"><div className="absolute left-8 top-8 grid size-28 place-items-center border-8 border-[#D52B1E] bg-[#FFF8EA] text-6xl text-[#D52B1E] shadow-[10px_10px_0_#D52B1E]" aria-hidden="true">＋</div><div className="relative mx-auto max-w-5xl text-center"><p className="flex items-center justify-center gap-2 text-sm font-black uppercase tracking-[0.25em] text-[#E6F0EA]"><Timer size={16} /> وقتك · خطتك · سويسرا</p><h1 className="mt-6 text-5xl font-black leading-[1.08] sm:text-7xl">رتّب وقتك مع القرآن والعربية</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-9 text-[#FFF8EA]/85">من زيورخ وجنيف إلى بازل وبرن، اختر الوقت الذي يناسبك ثم تعرّف إلى الباقة المناسبة. التواصل مع الأكاديمية باللغة العربية.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="#switzerland-plans" className="rounded-full bg-[#D52B1E] px-6 py-3 font-black text-white">افتح قرص الوقت</a><a href={trialUrl} target="_blank" rel="noreferrer" className="rounded-full border border-[#FFF8EA] px-6 py-3 font-black">احجز الحصة التجريبية</a></div></div></section>
    <section lang="de" className="bg-[#FFF8EA] px-5 py-12 sm:px-8" aria-labelledby="switzerland-local-card-title"><div className="mx-auto max-w-5xl border-r-8 border-[#D52B1E] bg-[#E6F0EA] p-6 text-left text-[#17211F] sm:p-9"><p className="text-xs font-black tracking-[0.2em] text-[#164A41]">{switzerlandLandingConfig.localCard.title}</p><h2 id="switzerland-local-card-title" className="mt-3 text-2xl font-black sm:text-3xl">{switzerlandLandingConfig.localCard.heading}</h2><p className="mt-4 max-w-4xl text-lg leading-8">{switzerlandLandingConfig.localCard.body}</p></div></section>
    <section className="bg-[#FFF8EA] px-5 py-14 sm:px-8"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-2"><article className="rounded-[2.5rem] border-r-8 border-[#D52B1E] bg-white p-7 shadow-[8px_8px_0_#E6F0EA]"><span className="text-4xl text-[#D52B1E]">01</span><p className="mt-4 font-black text-[#164A41]">تحفيظ القرآن الكريم</p><h2 className="mt-3 text-3xl font-black">وقت ثابت للحفظ والمراجعة</h2><p className="mt-4 leading-8 text-[#17211F]/70">حصص فردية لتنظيم الحفظ والتسميع والمراجعة والقراءة وفق هدف الطالب، مع باقات واضحة بالفرنك السويسري.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full bg-[#164A41] px-5 py-3 font-black text-white">اسأل عن برنامج القرآن</a></article><article className="rounded-[2.5rem] border-r-8 border-[#164A41] bg-[#E6F0EA] p-7 shadow-[8px_8px_0_#D52B1E]"><span className="text-4xl text-[#164A41]">02</span><p className="mt-4 font-black text-[#D52B1E]">تأسيس اللغة العربية</p><h2 className="mt-3 text-3xl font-black">خطوات عملية للقراءة والفهم</h2><p className="mt-4 leading-8 text-[#17211F]/70">مسار فردي لبناء أساس القراءة والفهم بالعربية، يبدأ من مستوى الطالب وهدفه التعليمي.</p><a href={packageUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-full border-2 border-[#164A41] px-5 py-3 font-black">اسأل عن برنامج العربية</a></article></div></section>
    <SwitzerlandVideoStack videos={videos} />
    <section className="bg-[#FFF8EA] px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-start gap-4"><MapPin className="mt-1 text-[#D52B1E]" /><div><p className="text-sm font-black text-[#164A41]">السياق المحلي</p><h2 className="mt-2 text-3xl font-black">التعلم أونلاين من مدن سويسرا</h2><p className="mt-4 max-w-3xl leading-8 text-[#17211F]/70">يمكنك التعلم أونلاين من زيورخ أو جنيف أو بازل أو برن. المدن المذكورة نطاق جغرافي للصفحة، ولا توجد بها مقرات أو فروع أو أماكن تدريس تابعة للأكاديمية.</p><div className="mt-6 flex flex-wrap gap-2">{cities.map((city) => <span key={city} className="rounded-full border border-[#E6F0EA] bg-white px-4 py-2 text-sm font-bold">{city}</span>)}</div><p className="mt-5 flex items-center gap-2 text-sm font-bold text-[#164A41]"><Clock3 size={16} /> {areaData.timezones.find((timezone) => timezone.is_primary)?.label_ar || switzerlandLandingConfig.timezone}</p></div></div></div></section>
    <SwitzerlandTimeDial whatsapp={packageUrl} quranPrices={quranPrices} arabicPrices={arabicPrices} />
    <section className="bg-[#164A41] px-5 py-16 text-[#FFF8EA] sm:px-8"><div className="mx-auto max-w-5xl"><p className="text-sm font-black text-[#D52B1E]">أسئلة شائعة</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">إجابات واضحة قبل التسجيل</h2><div className="mt-8 grid gap-3 sm:grid-cols-2">{faq.map(([question, answer], index) => <details key={question} className="rounded-2xl border border-[#E6F0EA]/20 bg-[#17211F]/25 p-5"><summary className="cursor-pointer font-black text-[#FFF8EA]"><span className="me-3 text-[#D52B1E]">0{index + 1}</span>{question}</summary><p className="mt-4 leading-7 text-[#FFF8EA]/75">{answer}</p></details>)}</div></div></section>
    <section className="bg-[#D52B1E] px-5 py-16 text-center text-white sm:px-8"><div className="mx-auto max-w-3xl"><h2 className="text-4xl font-black">ابدأ تنظيم خطتك</h2><p className="mt-4 leading-8">اذكر مدينتك والبرنامج الذي تريده والوقت المناسب لك، وابدأ التواصل باللغة العربية.</p><a href={trialUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#FFF8EA] px-6 py-3 font-black text-[#164A41]"><MessageCircle size={18} /> أريد الحصة التجريبية</a></div></section>
    <footer className="border-t-8 border-[#E6F0EA] bg-[#17211F] px-5 py-8 text-[#FFF8EA] sm:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-black tracking-wide">سويسرا · {new Date().getFullYear()}</span><nav aria-label="روابط صفحة سويسرا" className="flex flex-wrap gap-x-5 gap-y-2 text-sm font-bold text-[#FFF8EA]/85"><Link href="/">الرئيسية</Link><Link href="/games">الألعاب والمسابقات</Link><Link href="/library">المكتبة</Link><Link href="/contact">التواصل</Link><Link href="/privacy">الخصوصية</Link><Link href="/terms">الشروط</Link></nav></div><details className="mt-6 border-t border-white/15 pt-5"><summary className="cursor-pointer text-sm font-black text-[#D52B1E]">صفحاتنا حسب الدولة</summary><nav aria-label="كل صفحات الدول" className="mt-4 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{countryPages.map((country) => <Link key={country.href} href={country.href} className="rounded-md border border-white/15 px-3 py-2 text-sm text-[#FFF8EA]/85 transition hover:border-[#D52B1E] hover:text-white"><span className="me-2" aria-hidden="true">{country.flag}</span>{country.label}</Link>)}</nav></details></div></footer>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
  </main>
}
