'use client'

import { useState } from "react"
import Image from "next/image"
import { Play } from "lucide-react"
import { VideoPlayer } from "@/components/VideoPlayer"
import type { LandingVideo } from "@/lib/classroom-videos"

export function PortugalNauticalVideo({ videos }: { videos: LandingVideo[] }) { const [selected, setSelected] = useState<LandingVideo | null>(null); const video = videos.find((item) => item.showOnLandingPages); return <section className="bg-[#E0F2FE] px-5 py-20 sm:px-8"><div className="mx-auto max-w-5xl"><p className="text-xs font-black tracking-[0.28em] text-[#075985]">المفكرة البحرية · صفحة المشاهدة</p><h2 className="mt-4 text-4xl font-black text-[#123047] sm:text-6xl">شاهد مثالًا مرئيًا على طبيعة المحتوى</h2>{video ? <button type="button" onClick={() => setSelected(video)} className="group mt-10 grid w-full overflow-hidden rounded-[2rem] border-2 border-[#075985] bg-white text-right shadow-[10px_10px_0_#F4D7A1] md:grid-cols-[1.35fr_0.65fr]"><div className="relative h-72 bg-[#075985] md:h-96">{video.thumbnail_url ? <Image loader={({ src }) => src} src={video.thumbnail_url} alt={video.title_ar} fill sizes="650px" className="object-cover transition-transform duration-300 group-hover:scale-105 motion-reduce:transition-none" /> : null}<span className="absolute inset-0 grid place-items-center bg-[#075985]/25"><span className="grid size-16 place-items-center rounded-full bg-[#F4D7A1] text-[#123047]"><Play size={25} fill="currentColor" /></span></span></div><div className="flex flex-col justify-center p-8"><span className="text-sm font-black text-[#0F766E]">مقطع من محتوى الأكاديمية</span><p className="mt-4 text-2xl font-black text-[#123047]">{video.title_ar}</p><p className="mt-4 leading-8 text-[#123047]/70">{video.title_ar} — مثال مرئي من الدروس المنشورة.</p></div></button> : <p className="mt-8 rounded-2xl border-2 border-[#CBD5E1] bg-white p-6 font-bold text-[#123047]">محتوى التعريف المرئي سيظهر من المواد المنشورة.</p>}{selected ? <VideoPlayer isOpen videoId={selected.youtube_embed_id} title={selected.title_ar} onClose={() => setSelected(null)} /> : null}</div></section> }
